database:
  connection: ./password_manager.db
log:
  level: debug
  file: ""
  format: "text" # Log format: json, text, or yaml
  pretty_print: false
  max_backups: 5 # Number of backup log files to keep
  max_age_days: 30 # Days to keep log files
  max_size_mb: 5 # Size threshold in bytes (5MB)
  rotation_method: "hybrid" # Rotation method: size, time, hybrid
master_key: "EcxBWOnjRD8kLRBf/Eg4scrSZ0yFIz46kIEAeQ8+iqA=" # Replace with a secure 32-byte key
jwt_secret: "/MTzbV/S7muGfaUyxtlsqadtSr/xejboGnZK+d5ej/Tg3GSvWA5XfFHEvjYQ+4ES" # Replace with a secure secret
bootstrap_token: ff89e2e6-239c-4f7f-b2c2-84cdef6cf0ca
