database:
  connection: ./password_manager.db
log:
  level: debug
  file: password-manager.log
  max_size_mb: 10
  max_backups: 5
  max_age_days: 30
api:
  port: 8080
master_key: "EcxBWOnjRD8kLRBf/Eg4scrSZ0yFIz46kIEAeQ8+iqA=" # Replace with a secure 32-byte key
jwt_secret: "/MTzbV/S7muGfaUyxtlsqadtSr/xejboGnZK+d5ej/Tg3GSvWA5XfFHEvjYQ+4ES" # Replace with a secure secret
