version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  sqlite:
    image: nouchka/sqlite3:latest
    volumes:
      - ~/sqlite_data:/sqlite_data
    command: /bin/sh -c "sqlite3 /sqlite_data/mydatabase.db"
    networks:
      - db_network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - db_network

volumes:
  postgres_data:
  sqlite_data:
  mongo_data:

networks:
  db_network:
    driver: bridge