// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "rocketvault/model"

	mock "github.com/stretchr/testify/mock"

	repositories "rocketvault/internal/repositories"

	time "time"

	uuid "github.com/google/uuid"
)

// MockSecretRepositoryInterface is an autogenerated mock type for the SecretRepositoryInterface type
type MockSecretRepositoryInterface struct {
	mock.Mock
}

type MockSecretRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretRepositoryInterface) EXPECT() *MockSecretRepositoryInterface_Expecter {
	return &MockSecretRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, secret
func (_m *MockSecretRepositoryInterface) Create(ctx context.Context, secret *model.Secret) error {
	ret := _m.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Secret) error); ok {
		r0 = rf(ctx, secret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSecretRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - secret *model.Secret
func (_e *MockSecretRepositoryInterface_Expecter) Create(ctx interface{}, secret interface{}) *MockSecretRepositoryInterface_Create_Call {
	return &MockSecretRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, secret)}
}

func (_c *MockSecretRepositoryInterface_Create_Call) Run(run func(ctx context.Context, secret *model.Secret)) *MockSecretRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Secret))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_Create_Call) Return(_a0 error) *MockSecretRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepositoryInterface_Create_Call) RunAndReturn(run func(context.Context, *model.Secret) error) *MockSecretRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSecretRepositoryInterface) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecretRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSecretRepositoryInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockSecretRepositoryInterface_Delete_Call {
	return &MockSecretRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSecretRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSecretRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_Delete_Call) Return(_a0 error) *MockSecretRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepositoryInterface_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSecretRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExportSecrets provides a mock function with given fields: ctx, options
func (_m *MockSecretRepositoryInterface) ExportSecrets(ctx context.Context, options model.ExportOptions) ([]byte, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ExportSecrets")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ExportOptions) ([]byte, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ExportOptions) []byte); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ExportOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepositoryInterface_ExportSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportSecrets'
type MockSecretRepositoryInterface_ExportSecrets_Call struct {
	*mock.Call
}

// ExportSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - options model.ExportOptions
func (_e *MockSecretRepositoryInterface_Expecter) ExportSecrets(ctx interface{}, options interface{}) *MockSecretRepositoryInterface_ExportSecrets_Call {
	return &MockSecretRepositoryInterface_ExportSecrets_Call{Call: _e.mock.On("ExportSecrets", ctx, options)}
}

func (_c *MockSecretRepositoryInterface_ExportSecrets_Call) Run(run func(ctx context.Context, options model.ExportOptions)) *MockSecretRepositoryInterface_ExportSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ExportOptions))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_ExportSecrets_Call) Return(_a0 []byte, _a1 error) *MockSecretRepositoryInterface_ExportSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepositoryInterface_ExportSecrets_Call) RunAndReturn(run func(context.Context, model.ExportOptions) ([]byte, error)) *MockSecretRepositoryInterface_ExportSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestVersion provides a mock function with given fields: ctx, secretID
func (_m *MockSecretRepositoryInterface) GetLatestVersion(ctx context.Context, secretID uuid.UUID) (*model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersion")
	}

	var r0 *model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.SecretVersion, error)); ok {
		return rf(ctx, secretID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.SecretVersion); ok {
		r0 = rf(ctx, secretID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, secretID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepositoryInterface_GetLatestVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestVersion'
type MockSecretRepositoryInterface_GetLatestVersion_Call struct {
	*mock.Call
}

// GetLatestVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
func (_e *MockSecretRepositoryInterface_Expecter) GetLatestVersion(ctx interface{}, secretID interface{}) *MockSecretRepositoryInterface_GetLatestVersion_Call {
	return &MockSecretRepositoryInterface_GetLatestVersion_Call{Call: _e.mock.On("GetLatestVersion", ctx, secretID)}
}

func (_c *MockSecretRepositoryInterface_GetLatestVersion_Call) Run(run func(ctx context.Context, secretID uuid.UUID)) *MockSecretRepositoryInterface_GetLatestVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_GetLatestVersion_Call) Return(_a0 *model.SecretVersion, _a1 error) *MockSecretRepositoryInterface_GetLatestVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepositoryInterface_GetLatestVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.SecretVersion, error)) *MockSecretRepositoryInterface_GetLatestVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with given fields: ctx, secretID, version
func (_m *MockSecretRepositoryInterface) GetVersion(ctx context.Context, secretID uuid.UUID, version int) (*model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID, version)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 *model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (*model.SecretVersion, error)); ok {
		return rf(ctx, secretID, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) *model.SecretVersion); ok {
		r0 = rf(ctx, secretID, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, secretID, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepositoryInterface_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockSecretRepositoryInterface_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - version int
func (_e *MockSecretRepositoryInterface_Expecter) GetVersion(ctx interface{}, secretID interface{}, version interface{}) *MockSecretRepositoryInterface_GetVersion_Call {
	return &MockSecretRepositoryInterface_GetVersion_Call{Call: _e.mock.On("GetVersion", ctx, secretID, version)}
}

func (_c *MockSecretRepositoryInterface_GetVersion_Call) Run(run func(ctx context.Context, secretID uuid.UUID, version int)) *MockSecretRepositoryInterface_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_GetVersion_Call) Return(_a0 *model.SecretVersion, _a1 error) *MockSecretRepositoryInterface_GetVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepositoryInterface_GetVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) (*model.SecretVersion, error)) *MockSecretRepositoryInterface_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersions provides a mock function with given fields: ctx, secretID
func (_m *MockSecretRepositoryInterface) GetVersions(ctx context.Context, secretID uuid.UUID) ([]model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID)

	if len(ret) == 0 {
		panic("no return value specified for GetVersions")
	}

	var r0 []model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.SecretVersion, error)); ok {
		return rf(ctx, secretID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.SecretVersion); ok {
		r0 = rf(ctx, secretID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, secretID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepositoryInterface_GetVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersions'
type MockSecretRepositoryInterface_GetVersions_Call struct {
	*mock.Call
}

// GetVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
func (_e *MockSecretRepositoryInterface_Expecter) GetVersions(ctx interface{}, secretID interface{}) *MockSecretRepositoryInterface_GetVersions_Call {
	return &MockSecretRepositoryInterface_GetVersions_Call{Call: _e.mock.On("GetVersions", ctx, secretID)}
}

func (_c *MockSecretRepositoryInterface_GetVersions_Call) Run(run func(ctx context.Context, secretID uuid.UUID)) *MockSecretRepositoryInterface_GetVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_GetVersions_Call) Return(_a0 []model.SecretVersion, _a1 error) *MockSecretRepositoryInterface_GetVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepositoryInterface_GetVersions_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.SecretVersion, error)) *MockSecretRepositoryInterface_GetVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ImportSecrets provides a mock function with given fields: ctx, data, options
func (_m *MockSecretRepositoryInterface) ImportSecrets(ctx context.Context, data []byte, options model.ImportOptions) (int, error) {
	ret := _m.Called(ctx, data, options)

	if len(ret) == 0 {
		panic("no return value specified for ImportSecrets")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, model.ImportOptions) (int, error)); ok {
		return rf(ctx, data, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, model.ImportOptions) int); ok {
		r0 = rf(ctx, data, options)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, model.ImportOptions) error); ok {
		r1 = rf(ctx, data, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepositoryInterface_ImportSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportSecrets'
type MockSecretRepositoryInterface_ImportSecrets_Call struct {
	*mock.Call
}

// ImportSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
//   - options model.ImportOptions
func (_e *MockSecretRepositoryInterface_Expecter) ImportSecrets(ctx interface{}, data interface{}, options interface{}) *MockSecretRepositoryInterface_ImportSecrets_Call {
	return &MockSecretRepositoryInterface_ImportSecrets_Call{Call: _e.mock.On("ImportSecrets", ctx, data, options)}
}

func (_c *MockSecretRepositoryInterface_ImportSecrets_Call) Run(run func(ctx context.Context, data []byte, options model.ImportOptions)) *MockSecretRepositoryInterface_ImportSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(model.ImportOptions))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_ImportSecrets_Call) Return(_a0 int, _a1 error) *MockSecretRepositoryInterface_ImportSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepositoryInterface_ImportSecrets_Call) RunAndReturn(run func(context.Context, []byte, model.ImportOptions) (int, error)) *MockSecretRepositoryInterface_ImportSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, scope, filter
func (_m *MockSecretRepositoryInterface) List(ctx context.Context, scope model.Scope, filter repositories.SecretFilter) ([]model.Secret, error) {
	ret := _m.Called(ctx, scope, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, repositories.SecretFilter) ([]model.Secret, error)); ok {
		return rf(ctx, scope, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, repositories.SecretFilter) []model.Secret); ok {
		r0 = rf(ctx, scope, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope, repositories.SecretFilter) error); ok {
		r1 = rf(ctx, scope, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSecretRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
//   - filter repositories.SecretFilter
func (_e *MockSecretRepositoryInterface_Expecter) List(ctx interface{}, scope interface{}, filter interface{}) *MockSecretRepositoryInterface_List_Call {
	return &MockSecretRepositoryInterface_List_Call{Call: _e.mock.On("List", ctx, scope, filter)}
}

func (_c *MockSecretRepositoryInterface_List_Call) Run(run func(ctx context.Context, scope model.Scope, filter repositories.SecretFilter)) *MockSecretRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope), args[2].(repositories.SecretFilter))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_List_Call) Return(_a0 []model.Secret, _a1 error) *MockSecretRepositoryInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepositoryInterface_List_Call) RunAndReturn(run func(context.Context, model.Scope, repositories.SecretFilter) ([]model.Secret, error)) *MockSecretRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeSecret provides a mock function with given fields: ctx, id
func (_m *MockSecretRepositoryInterface) PurgeSecret(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PurgeSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepositoryInterface_PurgeSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeSecret'
type MockSecretRepositoryInterface_PurgeSecret_Call struct {
	*mock.Call
}

// PurgeSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSecretRepositoryInterface_Expecter) PurgeSecret(ctx interface{}, id interface{}) *MockSecretRepositoryInterface_PurgeSecret_Call {
	return &MockSecretRepositoryInterface_PurgeSecret_Call{Call: _e.mock.On("PurgeSecret", ctx, id)}
}

func (_c *MockSecretRepositoryInterface_PurgeSecret_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSecretRepositoryInterface_PurgeSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_PurgeSecret_Call) Return(_a0 error) *MockSecretRepositoryInterface_PurgeSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepositoryInterface_PurgeSecret_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSecretRepositoryInterface_PurgeSecret_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: ctx, id, scope
func (_m *MockSecretRepositoryInterface) Read(ctx context.Context, id uuid.UUID, scope model.Scope) (*model.Secret, error) {
	ret := _m.Called(ctx, id, scope)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) (*model.Secret, error)); ok {
		return rf(ctx, id, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) *model.Secret); ok {
		r0 = rf(ctx, id, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, id, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepositoryInterface_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockSecretRepositoryInterface_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - scope model.Scope
func (_e *MockSecretRepositoryInterface_Expecter) Read(ctx interface{}, id interface{}, scope interface{}) *MockSecretRepositoryInterface_Read_Call {
	return &MockSecretRepositoryInterface_Read_Call{Call: _e.mock.On("Read", ctx, id, scope)}
}

func (_c *MockSecretRepositoryInterface_Read_Call) Run(run func(ctx context.Context, id uuid.UUID, scope model.Scope)) *MockSecretRepositoryInterface_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_Read_Call) Return(_a0 *model.Secret, _a1 error) *MockSecretRepositoryInterface_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepositoryInterface_Read_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) (*model.Secret, error)) *MockSecretRepositoryInterface_Read_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverSecret provides a mock function with given fields: ctx, id
func (_m *MockSecretRepositoryInterface) RecoverSecret(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RecoverSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepositoryInterface_RecoverSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverSecret'
type MockSecretRepositoryInterface_RecoverSecret_Call struct {
	*mock.Call
}

// RecoverSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSecretRepositoryInterface_Expecter) RecoverSecret(ctx interface{}, id interface{}) *MockSecretRepositoryInterface_RecoverSecret_Call {
	return &MockSecretRepositoryInterface_RecoverSecret_Call{Call: _e.mock.On("RecoverSecret", ctx, id)}
}

func (_c *MockSecretRepositoryInterface_RecoverSecret_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSecretRepositoryInterface_RecoverSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_RecoverSecret_Call) Return(_a0 error) *MockSecretRepositoryInterface_RecoverSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepositoryInterface_RecoverSecret_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSecretRepositoryInterface_RecoverSecret_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverVaultContents provides a mock function with given fields: ctx, vaultID, deletedAt
func (_m *MockSecretRepositoryInterface) RecoverVaultContents(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time) error {
	ret := _m.Called(ctx, vaultID, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for RecoverVaultContents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, vaultID, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepositoryInterface_RecoverVaultContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverVaultContents'
type MockSecretRepositoryInterface_RecoverVaultContents_Call struct {
	*mock.Call
}

// RecoverVaultContents is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID uuid.UUID
//   - deletedAt time.Time
func (_e *MockSecretRepositoryInterface_Expecter) RecoverVaultContents(ctx interface{}, vaultID interface{}, deletedAt interface{}) *MockSecretRepositoryInterface_RecoverVaultContents_Call {
	return &MockSecretRepositoryInterface_RecoverVaultContents_Call{Call: _e.mock.On("RecoverVaultContents", ctx, vaultID, deletedAt)}
}

func (_c *MockSecretRepositoryInterface_RecoverVaultContents_Call) Run(run func(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time)) *MockSecretRepositoryInterface_RecoverVaultContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_RecoverVaultContents_Call) Return(_a0 error) *MockSecretRepositoryInterface_RecoverVaultContents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepositoryInterface_RecoverVaultContents_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockSecretRepositoryInterface_RecoverVaultContents_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockSecretRepositoryInterface) SoftDelete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepositoryInterface_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockSecretRepositoryInterface_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSecretRepositoryInterface_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockSecretRepositoryInterface_SoftDelete_Call {
	return &MockSecretRepositoryInterface_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockSecretRepositoryInterface_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSecretRepositoryInterface_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_SoftDelete_Call) Return(_a0 error) *MockSecretRepositoryInterface_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepositoryInterface_SoftDelete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSecretRepositoryInterface_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteVaultContents provides a mock function with given fields: ctx, vaultID, deletedAt
func (_m *MockSecretRepositoryInterface) SoftDeleteVaultContents(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time) error {
	ret := _m.Called(ctx, vaultID, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteVaultContents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, vaultID, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepositoryInterface_SoftDeleteVaultContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteVaultContents'
type MockSecretRepositoryInterface_SoftDeleteVaultContents_Call struct {
	*mock.Call
}

// SoftDeleteVaultContents is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID uuid.UUID
//   - deletedAt time.Time
func (_e *MockSecretRepositoryInterface_Expecter) SoftDeleteVaultContents(ctx interface{}, vaultID interface{}, deletedAt interface{}) *MockSecretRepositoryInterface_SoftDeleteVaultContents_Call {
	return &MockSecretRepositoryInterface_SoftDeleteVaultContents_Call{Call: _e.mock.On("SoftDeleteVaultContents", ctx, vaultID, deletedAt)}
}

func (_c *MockSecretRepositoryInterface_SoftDeleteVaultContents_Call) Run(run func(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time)) *MockSecretRepositoryInterface_SoftDeleteVaultContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_SoftDeleteVaultContents_Call) Return(_a0 error) *MockSecretRepositoryInterface_SoftDeleteVaultContents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepositoryInterface_SoftDeleteVaultContents_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockSecretRepositoryInterface_SoftDeleteVaultContents_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, secret, scope
func (_m *MockSecretRepositoryInterface) Update(ctx context.Context, secret *model.Secret, scope model.Scope) error {
	ret := _m.Called(ctx, secret, scope)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Secret, model.Scope) error); ok {
		r0 = rf(ctx, secret, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSecretRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - secret *model.Secret
//   - scope model.Scope
func (_e *MockSecretRepositoryInterface_Expecter) Update(ctx interface{}, secret interface{}, scope interface{}) *MockSecretRepositoryInterface_Update_Call {
	return &MockSecretRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, secret, scope)}
}

func (_c *MockSecretRepositoryInterface_Update_Call) Run(run func(ctx context.Context, secret *model.Secret, scope model.Scope)) *MockSecretRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Secret), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockSecretRepositoryInterface_Update_Call) Return(_a0 error) *MockSecretRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepositoryInterface_Update_Call) RunAndReturn(run func(context.Context, *model.Secret, model.Scope) error) *MockSecretRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretRepositoryInterface creates a new instance of MockSecretRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretRepositoryInterface {
	mock := &MockSecretRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
