// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "rocketvault/model"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockKeyRepositoryInterface is an autogenerated mock type for the KeyRepositoryInterface type
type MockKeyRepositoryInterface struct {
	mock.Mock
}

type MockKeyRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyRepositoryInterface) EXPECT() *MockKeyRepositoryInterface_Expecter {
	return &MockKeyRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, entity
func (_m *MockKeyRepositoryInterface) Create(ctx context.Context, entity *model.Key) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Key) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKeyRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *model.Key
func (_e *MockKeyRepositoryInterface_Expecter) Create(ctx interface{}, entity interface{}) *MockKeyRepositoryInterface_Create_Call {
	return &MockKeyRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockKeyRepositoryInterface_Create_Call) Run(run func(ctx context.Context, entity *model.Key)) *MockKeyRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Key))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_Create_Call) Return(_a0 error) *MockKeyRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_Create_Call) RunAndReturn(run func(context.Context, *model.Key) error) *MockKeyRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVersion provides a mock function with given fields: ctx, keyID, version, value
func (_m *MockKeyRepositoryInterface) CreateVersion(ctx context.Context, keyID uuid.UUID, version int, value string) error {
	ret := _m.Called(ctx, keyID, version, value)

	if len(ret) == 0 {
		panic("no return value specified for CreateVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, string) error); ok {
		r0 = rf(ctx, keyID, version, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_CreateVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVersion'
type MockKeyRepositoryInterface_CreateVersion_Call struct {
	*mock.Call
}

// CreateVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - version int
//   - value string
func (_e *MockKeyRepositoryInterface_Expecter) CreateVersion(ctx interface{}, keyID interface{}, version interface{}, value interface{}) *MockKeyRepositoryInterface_CreateVersion_Call {
	return &MockKeyRepositoryInterface_CreateVersion_Call{Call: _e.mock.On("CreateVersion", ctx, keyID, version, value)}
}

func (_c *MockKeyRepositoryInterface_CreateVersion_Call) Run(run func(ctx context.Context, keyID uuid.UUID, version int, value string)) *MockKeyRepositoryInterface_CreateVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_CreateVersion_Call) Return(_a0 error) *MockKeyRepositoryInterface_CreateVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_CreateVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, string) error) *MockKeyRepositoryInterface_CreateVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockKeyRepositoryInterface) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockKeyRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockKeyRepositoryInterface_Delete_Call {
	return &MockKeyRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockKeyRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockKeyRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_Delete_Call) Return(_a0 error) *MockKeyRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockKeyRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID, keyType, tags
func (_m *MockKeyRepositoryInterface) ListByUser(ctx context.Context, userID *uuid.UUID, keyType string, tags []string) ([]model.Key, error) {
	ret := _m.Called(ctx, userID, keyType, tags)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID, string, []string) ([]model.Key, error)); ok {
		return rf(ctx, userID, keyType, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID, string, []string) []model.Key); ok {
		r0 = rf(ctx, userID, keyType, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID, string, []string) error); ok {
		r1 = rf(ctx, userID, keyType, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockKeyRepositoryInterface_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *uuid.UUID
//   - keyType string
//   - tags []string
func (_e *MockKeyRepositoryInterface_Expecter) ListByUser(ctx interface{}, userID interface{}, keyType interface{}, tags interface{}) *MockKeyRepositoryInterface_ListByUser_Call {
	return &MockKeyRepositoryInterface_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, keyType, tags)}
}

func (_c *MockKeyRepositoryInterface_ListByUser_Call) Run(run func(ctx context.Context, userID *uuid.UUID, keyType string, tags []string)) *MockKeyRepositoryInterface_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*uuid.UUID), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_ListByUser_Call) Return(_a0 []model.Key, _a1 error) *MockKeyRepositoryInterface_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_ListByUser_Call) RunAndReturn(run func(context.Context, *uuid.UUID, string, []string) ([]model.Key, error)) *MockKeyRepositoryInterface_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListInVault provides a mock function with given fields: ctx, vaultID, keyType, tags
func (_m *MockKeyRepositoryInterface) ListInVault(ctx context.Context, vaultID uuid.UUID, keyType string, tags []string) ([]model.Key, error) {
	ret := _m.Called(ctx, vaultID, keyType, tags)

	if len(ret) == 0 {
		panic("no return value specified for ListInVault")
	}

	var r0 []model.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, []string) ([]model.Key, error)); ok {
		return rf(ctx, vaultID, keyType, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, []string) []model.Key); ok {
		r0 = rf(ctx, vaultID, keyType, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, []string) error); ok {
		r1 = rf(ctx, vaultID, keyType, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_ListInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInVault'
type MockKeyRepositoryInterface_ListInVault_Call struct {
	*mock.Call
}

// ListInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID uuid.UUID
//   - keyType string
//   - tags []string
func (_e *MockKeyRepositoryInterface_Expecter) ListInVault(ctx interface{}, vaultID interface{}, keyType interface{}, tags interface{}) *MockKeyRepositoryInterface_ListInVault_Call {
	return &MockKeyRepositoryInterface_ListInVault_Call{Call: _e.mock.On("ListInVault", ctx, vaultID, keyType, tags)}
}

func (_c *MockKeyRepositoryInterface_ListInVault_Call) Run(run func(ctx context.Context, vaultID uuid.UUID, keyType string, tags []string)) *MockKeyRepositoryInterface_ListInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_ListInVault_Call) Return(_a0 []model.Key, _a1 error) *MockKeyRepositoryInterface_ListInVault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_ListInVault_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, []string) ([]model.Key, error)) *MockKeyRepositoryInterface_ListInVault_Call {
	_c.Call.Return(run)
	return _c
}

// ListSoftDeleted provides a mock function with given fields: ctx, userID
func (_m *MockKeyRepositoryInterface) ListSoftDeleted(ctx context.Context, userID uuid.UUID) ([]*model.Key, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListSoftDeleted")
	}

	var r0 []*model.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Key, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Key); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_ListSoftDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSoftDeleted'
type MockKeyRepositoryInterface_ListSoftDeleted_Call struct {
	*mock.Call
}

// ListSoftDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) ListSoftDeleted(ctx interface{}, userID interface{}) *MockKeyRepositoryInterface_ListSoftDeleted_Call {
	return &MockKeyRepositoryInterface_ListSoftDeleted_Call{Call: _e.mock.On("ListSoftDeleted", ctx, userID)}
}

func (_c *MockKeyRepositoryInterface_ListSoftDeleted_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockKeyRepositoryInterface_ListSoftDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_ListSoftDeleted_Call) Return(_a0 []*model.Key, _a1 error) *MockKeyRepositoryInterface_ListSoftDeleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_ListSoftDeleted_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Key, error)) *MockKeyRepositoryInterface_ListSoftDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// ListVersions provides a mock function with given fields: ctx, keyID, userID
func (_m *MockKeyRepositoryInterface) ListVersions(ctx context.Context, keyID uuid.UUID, userID uuid.UUID) ([]model.KeyVersion, error) {
	ret := _m.Called(ctx, keyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListVersions")
	}

	var r0 []model.KeyVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]model.KeyVersion, error)); ok {
		return rf(ctx, keyID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []model.KeyVersion); ok {
		r0 = rf(ctx, keyID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.KeyVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, keyID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_ListVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVersions'
type MockKeyRepositoryInterface_ListVersions_Call struct {
	*mock.Call
}

// ListVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - userID uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) ListVersions(ctx interface{}, keyID interface{}, userID interface{}) *MockKeyRepositoryInterface_ListVersions_Call {
	return &MockKeyRepositoryInterface_ListVersions_Call{Call: _e.mock.On("ListVersions", ctx, keyID, userID)}
}

func (_c *MockKeyRepositoryInterface_ListVersions_Call) Run(run func(ctx context.Context, keyID uuid.UUID, userID uuid.UUID)) *MockKeyRepositoryInterface_ListVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_ListVersions_Call) Return(_a0 []model.KeyVersion, _a1 error) *MockKeyRepositoryInterface_ListVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_ListVersions_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]model.KeyVersion, error)) *MockKeyRepositoryInterface_ListVersions_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeKey provides a mock function with given fields: ctx, id
func (_m *MockKeyRepositoryInterface) PurgeKey(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PurgeKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_PurgeKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeKey'
type MockKeyRepositoryInterface_PurgeKey_Call struct {
	*mock.Call
}

// PurgeKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) PurgeKey(ctx interface{}, id interface{}) *MockKeyRepositoryInterface_PurgeKey_Call {
	return &MockKeyRepositoryInterface_PurgeKey_Call{Call: _e.mock.On("PurgeKey", ctx, id)}
}

func (_c *MockKeyRepositoryInterface_PurgeKey_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockKeyRepositoryInterface_PurgeKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_PurgeKey_Call) Return(_a0 error) *MockKeyRepositoryInterface_PurgeKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_PurgeKey_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockKeyRepositoryInterface_PurgeKey_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: ctx, id
func (_m *MockKeyRepositoryInterface) Read(ctx context.Context, id uuid.UUID) (*model.Key, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *model.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Key, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Key); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockKeyRepositoryInterface_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) Read(ctx interface{}, id interface{}) *MockKeyRepositoryInterface_Read_Call {
	return &MockKeyRepositoryInterface_Read_Call{Call: _e.mock.On("Read", ctx, id)}
}

func (_c *MockKeyRepositoryInterface_Read_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockKeyRepositoryInterface_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_Read_Call) Return(_a0 *model.Key, _a1 error) *MockKeyRepositoryInterface_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_Read_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Key, error)) *MockKeyRepositoryInterface_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDeleted provides a mock function with given fields: ctx, id
func (_m *MockKeyRepositoryInterface) ReadDeleted(ctx context.Context, id uuid.UUID) (*model.Key, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ReadDeleted")
	}

	var r0 *model.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Key, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Key); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_ReadDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDeleted'
type MockKeyRepositoryInterface_ReadDeleted_Call struct {
	*mock.Call
}

// ReadDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) ReadDeleted(ctx interface{}, id interface{}) *MockKeyRepositoryInterface_ReadDeleted_Call {
	return &MockKeyRepositoryInterface_ReadDeleted_Call{Call: _e.mock.On("ReadDeleted", ctx, id)}
}

func (_c *MockKeyRepositoryInterface_ReadDeleted_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockKeyRepositoryInterface_ReadDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_ReadDeleted_Call) Return(_a0 *model.Key, _a1 error) *MockKeyRepositoryInterface_ReadDeleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_ReadDeleted_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Key, error)) *MockKeyRepositoryInterface_ReadDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// ReadInVault provides a mock function with given fields: ctx, id, vaultID
func (_m *MockKeyRepositoryInterface) ReadInVault(ctx context.Context, id uuid.UUID, vaultID uuid.UUID) (*model.Key, error) {
	ret := _m.Called(ctx, id, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for ReadInVault")
	}

	var r0 *model.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Key, error)); ok {
		return rf(ctx, id, vaultID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Key); ok {
		r0 = rf(ctx, id, vaultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, vaultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepositoryInterface_ReadInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadInVault'
type MockKeyRepositoryInterface_ReadInVault_Call struct {
	*mock.Call
}

// ReadInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - vaultID uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) ReadInVault(ctx interface{}, id interface{}, vaultID interface{}) *MockKeyRepositoryInterface_ReadInVault_Call {
	return &MockKeyRepositoryInterface_ReadInVault_Call{Call: _e.mock.On("ReadInVault", ctx, id, vaultID)}
}

func (_c *MockKeyRepositoryInterface_ReadInVault_Call) Run(run func(ctx context.Context, id uuid.UUID, vaultID uuid.UUID)) *MockKeyRepositoryInterface_ReadInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_ReadInVault_Call) Return(_a0 *model.Key, _a1 error) *MockKeyRepositoryInterface_ReadInVault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepositoryInterface_ReadInVault_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.Key, error)) *MockKeyRepositoryInterface_ReadInVault_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverKey provides a mock function with given fields: ctx, id
func (_m *MockKeyRepositoryInterface) RecoverKey(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RecoverKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_RecoverKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverKey'
type MockKeyRepositoryInterface_RecoverKey_Call struct {
	*mock.Call
}

// RecoverKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) RecoverKey(ctx interface{}, id interface{}) *MockKeyRepositoryInterface_RecoverKey_Call {
	return &MockKeyRepositoryInterface_RecoverKey_Call{Call: _e.mock.On("RecoverKey", ctx, id)}
}

func (_c *MockKeyRepositoryInterface_RecoverKey_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockKeyRepositoryInterface_RecoverKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_RecoverKey_Call) Return(_a0 error) *MockKeyRepositoryInterface_RecoverKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_RecoverKey_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockKeyRepositoryInterface_RecoverKey_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverVaultContents provides a mock function with given fields: ctx, vaultID, deletedAt
func (_m *MockKeyRepositoryInterface) RecoverVaultContents(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time) error {
	ret := _m.Called(ctx, vaultID, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for RecoverVaultContents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, vaultID, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_RecoverVaultContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverVaultContents'
type MockKeyRepositoryInterface_RecoverVaultContents_Call struct {
	*mock.Call
}

// RecoverVaultContents is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID uuid.UUID
//   - deletedAt time.Time
func (_e *MockKeyRepositoryInterface_Expecter) RecoverVaultContents(ctx interface{}, vaultID interface{}, deletedAt interface{}) *MockKeyRepositoryInterface_RecoverVaultContents_Call {
	return &MockKeyRepositoryInterface_RecoverVaultContents_Call{Call: _e.mock.On("RecoverVaultContents", ctx, vaultID, deletedAt)}
}

func (_c *MockKeyRepositoryInterface_RecoverVaultContents_Call) Run(run func(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time)) *MockKeyRepositoryInterface_RecoverVaultContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_RecoverVaultContents_Call) Return(_a0 error) *MockKeyRepositoryInterface_RecoverVaultContents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_RecoverVaultContents_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockKeyRepositoryInterface_RecoverVaultContents_Call {
	_c.Call.Return(run)
	return _c
}

// SetPurgeProtection provides a mock function with given fields: ctx, id, enabled
func (_m *MockKeyRepositoryInterface) SetPurgeProtection(ctx context.Context, id uuid.UUID, enabled bool) error {
	ret := _m.Called(ctx, id, enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetPurgeProtection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, id, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_SetPurgeProtection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPurgeProtection'
type MockKeyRepositoryInterface_SetPurgeProtection_Call struct {
	*mock.Call
}

// SetPurgeProtection is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - enabled bool
func (_e *MockKeyRepositoryInterface_Expecter) SetPurgeProtection(ctx interface{}, id interface{}, enabled interface{}) *MockKeyRepositoryInterface_SetPurgeProtection_Call {
	return &MockKeyRepositoryInterface_SetPurgeProtection_Call{Call: _e.mock.On("SetPurgeProtection", ctx, id, enabled)}
}

func (_c *MockKeyRepositoryInterface_SetPurgeProtection_Call) Run(run func(ctx context.Context, id uuid.UUID, enabled bool)) *MockKeyRepositoryInterface_SetPurgeProtection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_SetPurgeProtection_Call) Return(_a0 error) *MockKeyRepositoryInterface_SetPurgeProtection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_SetPurgeProtection_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *MockKeyRepositoryInterface_SetPurgeProtection_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockKeyRepositoryInterface) SoftDelete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockKeyRepositoryInterface_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockKeyRepositoryInterface_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockKeyRepositoryInterface_SoftDelete_Call {
	return &MockKeyRepositoryInterface_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockKeyRepositoryInterface_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockKeyRepositoryInterface_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_SoftDelete_Call) Return(_a0 error) *MockKeyRepositoryInterface_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_SoftDelete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockKeyRepositoryInterface_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteVaultContents provides a mock function with given fields: ctx, vaultID, deletedAt
func (_m *MockKeyRepositoryInterface) SoftDeleteVaultContents(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time) error {
	ret := _m.Called(ctx, vaultID, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteVaultContents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, vaultID, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_SoftDeleteVaultContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteVaultContents'
type MockKeyRepositoryInterface_SoftDeleteVaultContents_Call struct {
	*mock.Call
}

// SoftDeleteVaultContents is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID uuid.UUID
//   - deletedAt time.Time
func (_e *MockKeyRepositoryInterface_Expecter) SoftDeleteVaultContents(ctx interface{}, vaultID interface{}, deletedAt interface{}) *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call {
	return &MockKeyRepositoryInterface_SoftDeleteVaultContents_Call{Call: _e.mock.On("SoftDeleteVaultContents", ctx, vaultID, deletedAt)}
}

func (_c *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call) Run(run func(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time)) *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call) Return(_a0 error) *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockKeyRepositoryInterface_SoftDeleteVaultContents_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, entity
func (_m *MockKeyRepositoryInterface) Update(ctx context.Context, entity *model.Key) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Key) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockKeyRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *model.Key
func (_e *MockKeyRepositoryInterface_Expecter) Update(ctx interface{}, entity interface{}) *MockKeyRepositoryInterface_Update_Call {
	return &MockKeyRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, entity)}
}

func (_c *MockKeyRepositoryInterface_Update_Call) Run(run func(ctx context.Context, entity *model.Key)) *MockKeyRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Key))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_Update_Call) Return(_a0 error) *MockKeyRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_Update_Call) RunAndReturn(run func(context.Context, *model.Key) error) *MockKeyRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRevocationStatus provides a mock function with given fields: ctx, id, revoked
func (_m *MockKeyRepositoryInterface) UpdateRevocationStatus(ctx context.Context, id uuid.UUID, revoked bool) error {
	ret := _m.Called(ctx, id, revoked)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRevocationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, id, revoked)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepositoryInterface_UpdateRevocationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRevocationStatus'
type MockKeyRepositoryInterface_UpdateRevocationStatus_Call struct {
	*mock.Call
}

// UpdateRevocationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - revoked bool
func (_e *MockKeyRepositoryInterface_Expecter) UpdateRevocationStatus(ctx interface{}, id interface{}, revoked interface{}) *MockKeyRepositoryInterface_UpdateRevocationStatus_Call {
	return &MockKeyRepositoryInterface_UpdateRevocationStatus_Call{Call: _e.mock.On("UpdateRevocationStatus", ctx, id, revoked)}
}

func (_c *MockKeyRepositoryInterface_UpdateRevocationStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, revoked bool)) *MockKeyRepositoryInterface_UpdateRevocationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockKeyRepositoryInterface_UpdateRevocationStatus_Call) Return(_a0 error) *MockKeyRepositoryInterface_UpdateRevocationStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepositoryInterface_UpdateRevocationStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *MockKeyRepositoryInterface_UpdateRevocationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeyRepositoryInterface creates a new instance of MockKeyRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyRepositoryInterface {
	mock := &MockKeyRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
