// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "rocketvault/model"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockCertificateRepositoryInterface is an autogenerated mock type for the CertificateRepositoryInterface type
type MockCertificateRepositoryInterface struct {
	mock.Mock
}

type MockCertificateRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCertificateRepositoryInterface) EXPECT() *MockCertificateRepositoryInterface_Expecter {
	return &MockCertificateRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, cert
func (_m *MockCertificateRepositoryInterface) Create(ctx context.Context, cert *model.Certificate) error {
	ret := _m.Called(ctx, cert)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Certificate) error); ok {
		r0 = rf(ctx, cert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCertificateRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cert *model.Certificate
func (_e *MockCertificateRepositoryInterface_Expecter) Create(ctx interface{}, cert interface{}) *MockCertificateRepositoryInterface_Create_Call {
	return &MockCertificateRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, cert)}
}

func (_c *MockCertificateRepositoryInterface_Create_Call) Run(run func(ctx context.Context, cert *model.Certificate)) *MockCertificateRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Certificate))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_Create_Call) Return(_a0 error) *MockCertificateRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateRepositoryInterface_Create_Call) RunAndReturn(run func(context.Context, *model.Certificate) error) *MockCertificateRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCertificateRepositoryInterface) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCertificateRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCertificateRepositoryInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockCertificateRepositoryInterface_Delete_Call {
	return &MockCertificateRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCertificateRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCertificateRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_Delete_Call) Return(_a0 error) *MockCertificateRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateRepositoryInterface_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCertificateRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx
func (_m *MockCertificateRepositoryInterface) ListAll(ctx context.Context) ([]model.Certificate, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Certificate, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Certificate); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateRepositoryInterface_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockCertificateRepositoryInterface_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCertificateRepositoryInterface_Expecter) ListAll(ctx interface{}) *MockCertificateRepositoryInterface_ListAll_Call {
	return &MockCertificateRepositoryInterface_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockCertificateRepositoryInterface_ListAll_Call) Run(run func(ctx context.Context)) *MockCertificateRepositoryInterface_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_ListAll_Call) Return(_a0 []model.Certificate, _a1 error) *MockCertificateRepositoryInterface_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateRepositoryInterface_ListAll_Call) RunAndReturn(run func(context.Context) ([]model.Certificate, error)) *MockCertificateRepositoryInterface_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID, tags
func (_m *MockCertificateRepositoryInterface) ListByUser(ctx context.Context, userID uuid.UUID, tags []string) ([]model.Certificate, error) {
	ret := _m.Called(ctx, userID, tags)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) ([]model.Certificate, error)); ok {
		return rf(ctx, userID, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) []model.Certificate); ok {
		r0 = rf(ctx, userID, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []string) error); ok {
		r1 = rf(ctx, userID, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateRepositoryInterface_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockCertificateRepositoryInterface_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tags []string
func (_e *MockCertificateRepositoryInterface_Expecter) ListByUser(ctx interface{}, userID interface{}, tags interface{}) *MockCertificateRepositoryInterface_ListByUser_Call {
	return &MockCertificateRepositoryInterface_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, tags)}
}

func (_c *MockCertificateRepositoryInterface_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, tags []string)) *MockCertificateRepositoryInterface_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]string))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_ListByUser_Call) Return(_a0 []model.Certificate, _a1 error) *MockCertificateRepositoryInterface_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateRepositoryInterface_ListByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, []string) ([]model.Certificate, error)) *MockCertificateRepositoryInterface_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListInVault provides a mock function with given fields: ctx, vaultID, tags
func (_m *MockCertificateRepositoryInterface) ListInVault(ctx context.Context, vaultID uuid.UUID, tags []string) ([]model.Certificate, error) {
	ret := _m.Called(ctx, vaultID, tags)

	if len(ret) == 0 {
		panic("no return value specified for ListInVault")
	}

	var r0 []model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) ([]model.Certificate, error)); ok {
		return rf(ctx, vaultID, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) []model.Certificate); ok {
		r0 = rf(ctx, vaultID, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []string) error); ok {
		r1 = rf(ctx, vaultID, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateRepositoryInterface_ListInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInVault'
type MockCertificateRepositoryInterface_ListInVault_Call struct {
	*mock.Call
}

// ListInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID uuid.UUID
//   - tags []string
func (_e *MockCertificateRepositoryInterface_Expecter) ListInVault(ctx interface{}, vaultID interface{}, tags interface{}) *MockCertificateRepositoryInterface_ListInVault_Call {
	return &MockCertificateRepositoryInterface_ListInVault_Call{Call: _e.mock.On("ListInVault", ctx, vaultID, tags)}
}

func (_c *MockCertificateRepositoryInterface_ListInVault_Call) Run(run func(ctx context.Context, vaultID uuid.UUID, tags []string)) *MockCertificateRepositoryInterface_ListInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]string))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_ListInVault_Call) Return(_a0 []model.Certificate, _a1 error) *MockCertificateRepositoryInterface_ListInVault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateRepositoryInterface_ListInVault_Call) RunAndReturn(run func(context.Context, uuid.UUID, []string) ([]model.Certificate, error)) *MockCertificateRepositoryInterface_ListInVault_Call {
	_c.Call.Return(run)
	return _c
}

// ListRevoked provides a mock function with given fields: ctx, userID
func (_m *MockCertificateRepositoryInterface) ListRevoked(ctx context.Context, userID uuid.UUID) ([]model.RevokedCertificate, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListRevoked")
	}

	var r0 []model.RevokedCertificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.RevokedCertificate, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.RevokedCertificate); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RevokedCertificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateRepositoryInterface_ListRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRevoked'
type MockCertificateRepositoryInterface_ListRevoked_Call struct {
	*mock.Call
}

// ListRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCertificateRepositoryInterface_Expecter) ListRevoked(ctx interface{}, userID interface{}) *MockCertificateRepositoryInterface_ListRevoked_Call {
	return &MockCertificateRepositoryInterface_ListRevoked_Call{Call: _e.mock.On("ListRevoked", ctx, userID)}
}

func (_c *MockCertificateRepositoryInterface_ListRevoked_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCertificateRepositoryInterface_ListRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_ListRevoked_Call) Return(_a0 []model.RevokedCertificate, _a1 error) *MockCertificateRepositoryInterface_ListRevoked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateRepositoryInterface_ListRevoked_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.RevokedCertificate, error)) *MockCertificateRepositoryInterface_ListRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// ListSoftDeleted provides a mock function with given fields: ctx, userID
func (_m *MockCertificateRepositoryInterface) ListSoftDeleted(ctx context.Context, userID uuid.UUID) ([]*model.Certificate, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListSoftDeleted")
	}

	var r0 []*model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Certificate, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Certificate); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateRepositoryInterface_ListSoftDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSoftDeleted'
type MockCertificateRepositoryInterface_ListSoftDeleted_Call struct {
	*mock.Call
}

// ListSoftDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCertificateRepositoryInterface_Expecter) ListSoftDeleted(ctx interface{}, userID interface{}) *MockCertificateRepositoryInterface_ListSoftDeleted_Call {
	return &MockCertificateRepositoryInterface_ListSoftDeleted_Call{Call: _e.mock.On("ListSoftDeleted", ctx, userID)}
}

func (_c *MockCertificateRepositoryInterface_ListSoftDeleted_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCertificateRepositoryInterface_ListSoftDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_ListSoftDeleted_Call) Return(_a0 []*model.Certificate, _a1 error) *MockCertificateRepositoryInterface_ListSoftDeleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateRepositoryInterface_ListSoftDeleted_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Certificate, error)) *MockCertificateRepositoryInterface_ListSoftDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeCertificate provides a mock function with given fields: ctx, id
func (_m *MockCertificateRepositoryInterface) PurgeCertificate(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PurgeCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateRepositoryInterface_PurgeCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeCertificate'
type MockCertificateRepositoryInterface_PurgeCertificate_Call struct {
	*mock.Call
}

// PurgeCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCertificateRepositoryInterface_Expecter) PurgeCertificate(ctx interface{}, id interface{}) *MockCertificateRepositoryInterface_PurgeCertificate_Call {
	return &MockCertificateRepositoryInterface_PurgeCertificate_Call{Call: _e.mock.On("PurgeCertificate", ctx, id)}
}

func (_c *MockCertificateRepositoryInterface_PurgeCertificate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCertificateRepositoryInterface_PurgeCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_PurgeCertificate_Call) Return(_a0 error) *MockCertificateRepositoryInterface_PurgeCertificate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateRepositoryInterface_PurgeCertificate_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCertificateRepositoryInterface_PurgeCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: ctx, id
func (_m *MockCertificateRepositoryInterface) Read(ctx context.Context, id uuid.UUID) (*model.Certificate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Certificate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Certificate); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateRepositoryInterface_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockCertificateRepositoryInterface_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCertificateRepositoryInterface_Expecter) Read(ctx interface{}, id interface{}) *MockCertificateRepositoryInterface_Read_Call {
	return &MockCertificateRepositoryInterface_Read_Call{Call: _e.mock.On("Read", ctx, id)}
}

func (_c *MockCertificateRepositoryInterface_Read_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCertificateRepositoryInterface_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_Read_Call) Return(_a0 *model.Certificate, _a1 error) *MockCertificateRepositoryInterface_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateRepositoryInterface_Read_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Certificate, error)) *MockCertificateRepositoryInterface_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadInVault provides a mock function with given fields: ctx, id, vaultID
func (_m *MockCertificateRepositoryInterface) ReadInVault(ctx context.Context, id uuid.UUID, vaultID uuid.UUID) (*model.Certificate, error) {
	ret := _m.Called(ctx, id, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for ReadInVault")
	}

	var r0 *model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Certificate, error)); ok {
		return rf(ctx, id, vaultID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Certificate); ok {
		r0 = rf(ctx, id, vaultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, vaultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateRepositoryInterface_ReadInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadInVault'
type MockCertificateRepositoryInterface_ReadInVault_Call struct {
	*mock.Call
}

// ReadInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - vaultID uuid.UUID
func (_e *MockCertificateRepositoryInterface_Expecter) ReadInVault(ctx interface{}, id interface{}, vaultID interface{}) *MockCertificateRepositoryInterface_ReadInVault_Call {
	return &MockCertificateRepositoryInterface_ReadInVault_Call{Call: _e.mock.On("ReadInVault", ctx, id, vaultID)}
}

func (_c *MockCertificateRepositoryInterface_ReadInVault_Call) Run(run func(ctx context.Context, id uuid.UUID, vaultID uuid.UUID)) *MockCertificateRepositoryInterface_ReadInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_ReadInVault_Call) Return(_a0 *model.Certificate, _a1 error) *MockCertificateRepositoryInterface_ReadInVault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateRepositoryInterface_ReadInVault_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.Certificate, error)) *MockCertificateRepositoryInterface_ReadInVault_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverCertificate provides a mock function with given fields: ctx, id
func (_m *MockCertificateRepositoryInterface) RecoverCertificate(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RecoverCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateRepositoryInterface_RecoverCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverCertificate'
type MockCertificateRepositoryInterface_RecoverCertificate_Call struct {
	*mock.Call
}

// RecoverCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCertificateRepositoryInterface_Expecter) RecoverCertificate(ctx interface{}, id interface{}) *MockCertificateRepositoryInterface_RecoverCertificate_Call {
	return &MockCertificateRepositoryInterface_RecoverCertificate_Call{Call: _e.mock.On("RecoverCertificate", ctx, id)}
}

func (_c *MockCertificateRepositoryInterface_RecoverCertificate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCertificateRepositoryInterface_RecoverCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_RecoverCertificate_Call) Return(_a0 error) *MockCertificateRepositoryInterface_RecoverCertificate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateRepositoryInterface_RecoverCertificate_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCertificateRepositoryInterface_RecoverCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverVaultContents provides a mock function with given fields: ctx, vaultID, deletedAt
func (_m *MockCertificateRepositoryInterface) RecoverVaultContents(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time) error {
	ret := _m.Called(ctx, vaultID, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for RecoverVaultContents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, vaultID, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateRepositoryInterface_RecoverVaultContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverVaultContents'
type MockCertificateRepositoryInterface_RecoverVaultContents_Call struct {
	*mock.Call
}

// RecoverVaultContents is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID uuid.UUID
//   - deletedAt time.Time
func (_e *MockCertificateRepositoryInterface_Expecter) RecoverVaultContents(ctx interface{}, vaultID interface{}, deletedAt interface{}) *MockCertificateRepositoryInterface_RecoverVaultContents_Call {
	return &MockCertificateRepositoryInterface_RecoverVaultContents_Call{Call: _e.mock.On("RecoverVaultContents", ctx, vaultID, deletedAt)}
}

func (_c *MockCertificateRepositoryInterface_RecoverVaultContents_Call) Run(run func(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time)) *MockCertificateRepositoryInterface_RecoverVaultContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_RecoverVaultContents_Call) Return(_a0 error) *MockCertificateRepositoryInterface_RecoverVaultContents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateRepositoryInterface_RecoverVaultContents_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockCertificateRepositoryInterface_RecoverVaultContents_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, id, serialNumber, name
func (_m *MockCertificateRepositoryInterface) Revoke(ctx context.Context, id uuid.UUID, serialNumber string, name string) error {
	ret := _m.Called(ctx, id, serialNumber, name)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = rf(ctx, id, serialNumber, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateRepositoryInterface_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockCertificateRepositoryInterface_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - serialNumber string
//   - name string
func (_e *MockCertificateRepositoryInterface_Expecter) Revoke(ctx interface{}, id interface{}, serialNumber interface{}, name interface{}) *MockCertificateRepositoryInterface_Revoke_Call {
	return &MockCertificateRepositoryInterface_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id, serialNumber, name)}
}

func (_c *MockCertificateRepositoryInterface_Revoke_Call) Run(run func(ctx context.Context, id uuid.UUID, serialNumber string, name string)) *MockCertificateRepositoryInterface_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_Revoke_Call) Return(_a0 error) *MockCertificateRepositoryInterface_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateRepositoryInterface_Revoke_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) error) *MockCertificateRepositoryInterface_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// SetPurgeProtection provides a mock function with given fields: ctx, id, enabled
func (_m *MockCertificateRepositoryInterface) SetPurgeProtection(ctx context.Context, id uuid.UUID, enabled bool) error {
	ret := _m.Called(ctx, id, enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetPurgeProtection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, id, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateRepositoryInterface_SetPurgeProtection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPurgeProtection'
type MockCertificateRepositoryInterface_SetPurgeProtection_Call struct {
	*mock.Call
}

// SetPurgeProtection is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - enabled bool
func (_e *MockCertificateRepositoryInterface_Expecter) SetPurgeProtection(ctx interface{}, id interface{}, enabled interface{}) *MockCertificateRepositoryInterface_SetPurgeProtection_Call {
	return &MockCertificateRepositoryInterface_SetPurgeProtection_Call{Call: _e.mock.On("SetPurgeProtection", ctx, id, enabled)}
}

func (_c *MockCertificateRepositoryInterface_SetPurgeProtection_Call) Run(run func(ctx context.Context, id uuid.UUID, enabled bool)) *MockCertificateRepositoryInterface_SetPurgeProtection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_SetPurgeProtection_Call) Return(_a0 error) *MockCertificateRepositoryInterface_SetPurgeProtection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateRepositoryInterface_SetPurgeProtection_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *MockCertificateRepositoryInterface_SetPurgeProtection_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockCertificateRepositoryInterface) SoftDelete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateRepositoryInterface_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockCertificateRepositoryInterface_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCertificateRepositoryInterface_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockCertificateRepositoryInterface_SoftDelete_Call {
	return &MockCertificateRepositoryInterface_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockCertificateRepositoryInterface_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCertificateRepositoryInterface_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_SoftDelete_Call) Return(_a0 error) *MockCertificateRepositoryInterface_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateRepositoryInterface_SoftDelete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCertificateRepositoryInterface_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteVaultContents provides a mock function with given fields: ctx, vaultID, deletedAt
func (_m *MockCertificateRepositoryInterface) SoftDeleteVaultContents(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time) error {
	ret := _m.Called(ctx, vaultID, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteVaultContents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, vaultID, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateRepositoryInterface_SoftDeleteVaultContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteVaultContents'
type MockCertificateRepositoryInterface_SoftDeleteVaultContents_Call struct {
	*mock.Call
}

// SoftDeleteVaultContents is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID uuid.UUID
//   - deletedAt time.Time
func (_e *MockCertificateRepositoryInterface_Expecter) SoftDeleteVaultContents(ctx interface{}, vaultID interface{}, deletedAt interface{}) *MockCertificateRepositoryInterface_SoftDeleteVaultContents_Call {
	return &MockCertificateRepositoryInterface_SoftDeleteVaultContents_Call{Call: _e.mock.On("SoftDeleteVaultContents", ctx, vaultID, deletedAt)}
}

func (_c *MockCertificateRepositoryInterface_SoftDeleteVaultContents_Call) Run(run func(ctx context.Context, vaultID uuid.UUID, deletedAt time.Time)) *MockCertificateRepositoryInterface_SoftDeleteVaultContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_SoftDeleteVaultContents_Call) Return(_a0 error) *MockCertificateRepositoryInterface_SoftDeleteVaultContents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateRepositoryInterface_SoftDeleteVaultContents_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockCertificateRepositoryInterface_SoftDeleteVaultContents_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, cert
func (_m *MockCertificateRepositoryInterface) Update(ctx context.Context, cert *model.Certificate) error {
	ret := _m.Called(ctx, cert)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Certificate) error); ok {
		r0 = rf(ctx, cert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCertificateRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - cert *model.Certificate
func (_e *MockCertificateRepositoryInterface_Expecter) Update(ctx interface{}, cert interface{}) *MockCertificateRepositoryInterface_Update_Call {
	return &MockCertificateRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, cert)}
}

func (_c *MockCertificateRepositoryInterface_Update_Call) Run(run func(ctx context.Context, cert *model.Certificate)) *MockCertificateRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Certificate))
	})
	return _c
}

func (_c *MockCertificateRepositoryInterface_Update_Call) Return(_a0 error) *MockCertificateRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateRepositoryInterface_Update_Call) RunAndReturn(run func(context.Context, *model.Certificate) error) *MockCertificateRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCertificateRepositoryInterface creates a new instance of MockCertificateRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCertificateRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCertificateRepositoryInterface {
	mock := &MockCertificateRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
