// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "rocketvault/model"

	mock "github.com/stretchr/testify/mock"

	secrets "rocketvault/internal/services/secrets"

	uuid "github.com/google/uuid"
)

// MockSecretService is an autogenerated mock type for the SecretService type
type MockSecretService struct {
	mock.Mock
}

type MockSecretService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretService) EXPECT() *MockSecretService_Expecter {
	return &MockSecretService_Expecter{mock: &_m.Mock}
}

// CreateSecret provides a mock function with given fields: ctx, req
func (_m *MockSecretService) CreateSecret(ctx context.Context, req secrets.CreateSecretRequest) (*model.Secret, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 *model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.CreateSecretRequest) (*model.Secret, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, secrets.CreateSecretRequest) *model.Secret); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, secrets.CreateSecretRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockSecretService_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.CreateSecretRequest
func (_e *MockSecretService_Expecter) CreateSecret(ctx interface{}, req interface{}) *MockSecretService_CreateSecret_Call {
	return &MockSecretService_CreateSecret_Call{Call: _e.mock.On("CreateSecret", ctx, req)}
}

func (_c *MockSecretService_CreateSecret_Call) Run(run func(ctx context.Context, req secrets.CreateSecretRequest)) *MockSecretService_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.CreateSecretRequest))
	})
	return _c
}

func (_c *MockSecretService_CreateSecret_Call) Return(_a0 *model.Secret, _a1 error) *MockSecretService_CreateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_CreateSecret_Call) RunAndReturn(run func(context.Context, secrets.CreateSecretRequest) (*model.Secret, error)) *MockSecretService_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function with given fields: ctx, secretID, userID
func (_m *MockSecretService) DeleteSecret(ctx context.Context, secretID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, secretID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, secretID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretService_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockSecretService_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - userID uuid.UUID
func (_e *MockSecretService_Expecter) DeleteSecret(ctx interface{}, secretID interface{}, userID interface{}) *MockSecretService_DeleteSecret_Call {
	return &MockSecretService_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, secretID, userID)}
}

func (_c *MockSecretService_DeleteSecret_Call) Run(run func(ctx context.Context, secretID uuid.UUID, userID uuid.UUID)) *MockSecretService_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretService_DeleteSecret_Call) Return(_a0 error) *MockSecretService_DeleteSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretService_DeleteSecret_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockSecretService_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecretInVault provides a mock function with given fields: ctx, secretID, vaultID
func (_m *MockSecretService) DeleteSecretInVault(ctx context.Context, secretID uuid.UUID, vaultID uuid.UUID) error {
	ret := _m.Called(ctx, secretID, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecretInVault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, secretID, vaultID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretService_DeleteSecretInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecretInVault'
type MockSecretService_DeleteSecretInVault_Call struct {
	*mock.Call
}

// DeleteSecretInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - vaultID uuid.UUID
func (_e *MockSecretService_Expecter) DeleteSecretInVault(ctx interface{}, secretID interface{}, vaultID interface{}) *MockSecretService_DeleteSecretInVault_Call {
	return &MockSecretService_DeleteSecretInVault_Call{Call: _e.mock.On("DeleteSecretInVault", ctx, secretID, vaultID)}
}

func (_c *MockSecretService_DeleteSecretInVault_Call) Run(run func(ctx context.Context, secretID uuid.UUID, vaultID uuid.UUID)) *MockSecretService_DeleteSecretInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretService_DeleteSecretInVault_Call) Return(_a0 error) *MockSecretService_DeleteSecretInVault_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretService_DeleteSecretInVault_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockSecretService_DeleteSecretInVault_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecretScoped provides a mock function with given fields: ctx, secretID, scope
func (_m *MockSecretService) DeleteSecretScoped(ctx context.Context, secretID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, secretID, scope)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecretScoped")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, secretID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretService_DeleteSecretScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecretScoped'
type MockSecretService_DeleteSecretScoped_Call struct {
	*mock.Call
}

// DeleteSecretScoped is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - scope model.Scope
func (_e *MockSecretService_Expecter) DeleteSecretScoped(ctx interface{}, secretID interface{}, scope interface{}) *MockSecretService_DeleteSecretScoped_Call {
	return &MockSecretService_DeleteSecretScoped_Call{Call: _e.mock.On("DeleteSecretScoped", ctx, secretID, scope)}
}

func (_c *MockSecretService_DeleteSecretScoped_Call) Run(run func(ctx context.Context, secretID uuid.UUID, scope model.Scope)) *MockSecretService_DeleteSecretScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockSecretService_DeleteSecretScoped_Call) Return(_a0 error) *MockSecretService_DeleteSecretScoped_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretService_DeleteSecretScoped_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockSecretService_DeleteSecretScoped_Call {
	_c.Call.Return(run)
	return _c
}

// ExportSecrets provides a mock function with given fields: ctx, req
func (_m *MockSecretService) ExportSecrets(ctx context.Context, req secrets.ExportSecretsRequest) ([]byte, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ExportSecrets")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.ExportSecretsRequest) ([]byte, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, secrets.ExportSecretsRequest) []byte); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, secrets.ExportSecretsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_ExportSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportSecrets'
type MockSecretService_ExportSecrets_Call struct {
	*mock.Call
}

// ExportSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.ExportSecretsRequest
func (_e *MockSecretService_Expecter) ExportSecrets(ctx interface{}, req interface{}) *MockSecretService_ExportSecrets_Call {
	return &MockSecretService_ExportSecrets_Call{Call: _e.mock.On("ExportSecrets", ctx, req)}
}

func (_c *MockSecretService_ExportSecrets_Call) Run(run func(ctx context.Context, req secrets.ExportSecretsRequest)) *MockSecretService_ExportSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.ExportSecretsRequest))
	})
	return _c
}

func (_c *MockSecretService_ExportSecrets_Call) Return(_a0 []byte, _a1 error) *MockSecretService_ExportSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_ExportSecrets_Call) RunAndReturn(run func(context.Context, secrets.ExportSecretsRequest) ([]byte, error)) *MockSecretService_ExportSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateSecret provides a mock function with given fields: ctx, req
func (_m *MockSecretService) GenerateSecret(ctx context.Context, req secrets.GenerateSecretRequest) (*model.Secret, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSecret")
	}

	var r0 *model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.GenerateSecretRequest) (*model.Secret, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, secrets.GenerateSecretRequest) *model.Secret); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, secrets.GenerateSecretRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GenerateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSecret'
type MockSecretService_GenerateSecret_Call struct {
	*mock.Call
}

// GenerateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.GenerateSecretRequest
func (_e *MockSecretService_Expecter) GenerateSecret(ctx interface{}, req interface{}) *MockSecretService_GenerateSecret_Call {
	return &MockSecretService_GenerateSecret_Call{Call: _e.mock.On("GenerateSecret", ctx, req)}
}

func (_c *MockSecretService_GenerateSecret_Call) Run(run func(ctx context.Context, req secrets.GenerateSecretRequest)) *MockSecretService_GenerateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.GenerateSecretRequest))
	})
	return _c
}

func (_c *MockSecretService_GenerateSecret_Call) Return(_a0 *model.Secret, _a1 error) *MockSecretService_GenerateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GenerateSecret_Call) RunAndReturn(run func(context.Context, secrets.GenerateSecretRequest) (*model.Secret, error)) *MockSecretService_GenerateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestSecretVersion provides a mock function with given fields: ctx, secretID, userID
func (_m *MockSecretService) GetLatestSecretVersion(ctx context.Context, secretID uuid.UUID, userID uuid.UUID) (*model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSecretVersion")
	}

	var r0 *model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.SecretVersion, error)); ok {
		return rf(ctx, secretID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.SecretVersion); ok {
		r0 = rf(ctx, secretID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, secretID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GetLatestSecretVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestSecretVersion'
type MockSecretService_GetLatestSecretVersion_Call struct {
	*mock.Call
}

// GetLatestSecretVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - userID uuid.UUID
func (_e *MockSecretService_Expecter) GetLatestSecretVersion(ctx interface{}, secretID interface{}, userID interface{}) *MockSecretService_GetLatestSecretVersion_Call {
	return &MockSecretService_GetLatestSecretVersion_Call{Call: _e.mock.On("GetLatestSecretVersion", ctx, secretID, userID)}
}

func (_c *MockSecretService_GetLatestSecretVersion_Call) Run(run func(ctx context.Context, secretID uuid.UUID, userID uuid.UUID)) *MockSecretService_GetLatestSecretVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretService_GetLatestSecretVersion_Call) Return(_a0 *model.SecretVersion, _a1 error) *MockSecretService_GetLatestSecretVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GetLatestSecretVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.SecretVersion, error)) *MockSecretService_GetLatestSecretVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestSecretVersionInVault provides a mock function with given fields: ctx, secretID, vaultID
func (_m *MockSecretService) GetLatestSecretVersionInVault(ctx context.Context, secretID uuid.UUID, vaultID uuid.UUID) (*model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSecretVersionInVault")
	}

	var r0 *model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.SecretVersion, error)); ok {
		return rf(ctx, secretID, vaultID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.SecretVersion); ok {
		r0 = rf(ctx, secretID, vaultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, secretID, vaultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GetLatestSecretVersionInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestSecretVersionInVault'
type MockSecretService_GetLatestSecretVersionInVault_Call struct {
	*mock.Call
}

// GetLatestSecretVersionInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - vaultID uuid.UUID
func (_e *MockSecretService_Expecter) GetLatestSecretVersionInVault(ctx interface{}, secretID interface{}, vaultID interface{}) *MockSecretService_GetLatestSecretVersionInVault_Call {
	return &MockSecretService_GetLatestSecretVersionInVault_Call{Call: _e.mock.On("GetLatestSecretVersionInVault", ctx, secretID, vaultID)}
}

func (_c *MockSecretService_GetLatestSecretVersionInVault_Call) Run(run func(ctx context.Context, secretID uuid.UUID, vaultID uuid.UUID)) *MockSecretService_GetLatestSecretVersionInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretService_GetLatestSecretVersionInVault_Call) Return(_a0 *model.SecretVersion, _a1 error) *MockSecretService_GetLatestSecretVersionInVault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GetLatestSecretVersionInVault_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.SecretVersion, error)) *MockSecretService_GetLatestSecretVersionInVault_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function with given fields: ctx, secretID, userID
func (_m *MockSecretService) GetSecret(ctx context.Context, secretID uuid.UUID, userID uuid.UUID) (*model.Secret, error) {
	ret := _m.Called(ctx, secretID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Secret, error)); ok {
		return rf(ctx, secretID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Secret); ok {
		r0 = rf(ctx, secretID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, secretID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockSecretService_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - userID uuid.UUID
func (_e *MockSecretService_Expecter) GetSecret(ctx interface{}, secretID interface{}, userID interface{}) *MockSecretService_GetSecret_Call {
	return &MockSecretService_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, secretID, userID)}
}

func (_c *MockSecretService_GetSecret_Call) Run(run func(ctx context.Context, secretID uuid.UUID, userID uuid.UUID)) *MockSecretService_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretService_GetSecret_Call) Return(_a0 *model.Secret, _a1 error) *MockSecretService_GetSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GetSecret_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.Secret, error)) *MockSecretService_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretInVault provides a mock function with given fields: ctx, secretID, vaultID
func (_m *MockSecretService) GetSecretInVault(ctx context.Context, secretID uuid.UUID, vaultID uuid.UUID) (*model.Secret, error) {
	ret := _m.Called(ctx, secretID, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretInVault")
	}

	var r0 *model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Secret, error)); ok {
		return rf(ctx, secretID, vaultID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Secret); ok {
		r0 = rf(ctx, secretID, vaultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, secretID, vaultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GetSecretInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretInVault'
type MockSecretService_GetSecretInVault_Call struct {
	*mock.Call
}

// GetSecretInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - vaultID uuid.UUID
func (_e *MockSecretService_Expecter) GetSecretInVault(ctx interface{}, secretID interface{}, vaultID interface{}) *MockSecretService_GetSecretInVault_Call {
	return &MockSecretService_GetSecretInVault_Call{Call: _e.mock.On("GetSecretInVault", ctx, secretID, vaultID)}
}

func (_c *MockSecretService_GetSecretInVault_Call) Run(run func(ctx context.Context, secretID uuid.UUID, vaultID uuid.UUID)) *MockSecretService_GetSecretInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretService_GetSecretInVault_Call) Return(_a0 *model.Secret, _a1 error) *MockSecretService_GetSecretInVault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GetSecretInVault_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.Secret, error)) *MockSecretService_GetSecretInVault_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretScoped provides a mock function with given fields: ctx, secretID, scope
func (_m *MockSecretService) GetSecretScoped(ctx context.Context, secretID uuid.UUID, scope model.Scope) (*model.Secret, error) {
	ret := _m.Called(ctx, secretID, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretScoped")
	}

	var r0 *model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) (*model.Secret, error)); ok {
		return rf(ctx, secretID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) *model.Secret); ok {
		r0 = rf(ctx, secretID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, secretID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GetSecretScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretScoped'
type MockSecretService_GetSecretScoped_Call struct {
	*mock.Call
}

// GetSecretScoped is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - scope model.Scope
func (_e *MockSecretService_Expecter) GetSecretScoped(ctx interface{}, secretID interface{}, scope interface{}) *MockSecretService_GetSecretScoped_Call {
	return &MockSecretService_GetSecretScoped_Call{Call: _e.mock.On("GetSecretScoped", ctx, secretID, scope)}
}

func (_c *MockSecretService_GetSecretScoped_Call) Run(run func(ctx context.Context, secretID uuid.UUID, scope model.Scope)) *MockSecretService_GetSecretScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockSecretService_GetSecretScoped_Call) Return(_a0 *model.Secret, _a1 error) *MockSecretService_GetSecretScoped_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GetSecretScoped_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) (*model.Secret, error)) *MockSecretService_GetSecretScoped_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretVersion provides a mock function with given fields: ctx, secretID, version, userID
func (_m *MockSecretService) GetSecretVersion(ctx context.Context, secretID uuid.UUID, version int, userID uuid.UUID) (*model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID, version, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretVersion")
	}

	var r0 *model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, uuid.UUID) (*model.SecretVersion, error)); ok {
		return rf(ctx, secretID, version, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, uuid.UUID) *model.SecretVersion); ok {
		r0 = rf(ctx, secretID, version, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, uuid.UUID) error); ok {
		r1 = rf(ctx, secretID, version, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GetSecretVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretVersion'
type MockSecretService_GetSecretVersion_Call struct {
	*mock.Call
}

// GetSecretVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - version int
//   - userID uuid.UUID
func (_e *MockSecretService_Expecter) GetSecretVersion(ctx interface{}, secretID interface{}, version interface{}, userID interface{}) *MockSecretService_GetSecretVersion_Call {
	return &MockSecretService_GetSecretVersion_Call{Call: _e.mock.On("GetSecretVersion", ctx, secretID, version, userID)}
}

func (_c *MockSecretService_GetSecretVersion_Call) Run(run func(ctx context.Context, secretID uuid.UUID, version int, userID uuid.UUID)) *MockSecretService_GetSecretVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretService_GetSecretVersion_Call) Return(_a0 *model.SecretVersion, _a1 error) *MockSecretService_GetSecretVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GetSecretVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, uuid.UUID) (*model.SecretVersion, error)) *MockSecretService_GetSecretVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretVersionInVault provides a mock function with given fields: ctx, secretID, version, vaultID
func (_m *MockSecretService) GetSecretVersionInVault(ctx context.Context, secretID uuid.UUID, version int, vaultID uuid.UUID) (*model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID, version, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretVersionInVault")
	}

	var r0 *model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, uuid.UUID) (*model.SecretVersion, error)); ok {
		return rf(ctx, secretID, version, vaultID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, uuid.UUID) *model.SecretVersion); ok {
		r0 = rf(ctx, secretID, version, vaultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, uuid.UUID) error); ok {
		r1 = rf(ctx, secretID, version, vaultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GetSecretVersionInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretVersionInVault'
type MockSecretService_GetSecretVersionInVault_Call struct {
	*mock.Call
}

// GetSecretVersionInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - version int
//   - vaultID uuid.UUID
func (_e *MockSecretService_Expecter) GetSecretVersionInVault(ctx interface{}, secretID interface{}, version interface{}, vaultID interface{}) *MockSecretService_GetSecretVersionInVault_Call {
	return &MockSecretService_GetSecretVersionInVault_Call{Call: _e.mock.On("GetSecretVersionInVault", ctx, secretID, version, vaultID)}
}

func (_c *MockSecretService_GetSecretVersionInVault_Call) Run(run func(ctx context.Context, secretID uuid.UUID, version int, vaultID uuid.UUID)) *MockSecretService_GetSecretVersionInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretService_GetSecretVersionInVault_Call) Return(_a0 *model.SecretVersion, _a1 error) *MockSecretService_GetSecretVersionInVault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GetSecretVersionInVault_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, uuid.UUID) (*model.SecretVersion, error)) *MockSecretService_GetSecretVersionInVault_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretVersions provides a mock function with given fields: ctx, secretID, userID
func (_m *MockSecretService) GetSecretVersions(ctx context.Context, secretID uuid.UUID, userID uuid.UUID) ([]model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretVersions")
	}

	var r0 []model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]model.SecretVersion, error)); ok {
		return rf(ctx, secretID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []model.SecretVersion); ok {
		r0 = rf(ctx, secretID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, secretID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GetSecretVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretVersions'
type MockSecretService_GetSecretVersions_Call struct {
	*mock.Call
}

// GetSecretVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - userID uuid.UUID
func (_e *MockSecretService_Expecter) GetSecretVersions(ctx interface{}, secretID interface{}, userID interface{}) *MockSecretService_GetSecretVersions_Call {
	return &MockSecretService_GetSecretVersions_Call{Call: _e.mock.On("GetSecretVersions", ctx, secretID, userID)}
}

func (_c *MockSecretService_GetSecretVersions_Call) Run(run func(ctx context.Context, secretID uuid.UUID, userID uuid.UUID)) *MockSecretService_GetSecretVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretService_GetSecretVersions_Call) Return(_a0 []model.SecretVersion, _a1 error) *MockSecretService_GetSecretVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GetSecretVersions_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]model.SecretVersion, error)) *MockSecretService_GetSecretVersions_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretVersionsInVault provides a mock function with given fields: ctx, secretID, vaultID
func (_m *MockSecretService) GetSecretVersionsInVault(ctx context.Context, secretID uuid.UUID, vaultID uuid.UUID) ([]model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretVersionsInVault")
	}

	var r0 []model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]model.SecretVersion, error)); ok {
		return rf(ctx, secretID, vaultID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []model.SecretVersion); ok {
		r0 = rf(ctx, secretID, vaultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, secretID, vaultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GetSecretVersionsInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretVersionsInVault'
type MockSecretService_GetSecretVersionsInVault_Call struct {
	*mock.Call
}

// GetSecretVersionsInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - vaultID uuid.UUID
func (_e *MockSecretService_Expecter) GetSecretVersionsInVault(ctx interface{}, secretID interface{}, vaultID interface{}) *MockSecretService_GetSecretVersionsInVault_Call {
	return &MockSecretService_GetSecretVersionsInVault_Call{Call: _e.mock.On("GetSecretVersionsInVault", ctx, secretID, vaultID)}
}

func (_c *MockSecretService_GetSecretVersionsInVault_Call) Run(run func(ctx context.Context, secretID uuid.UUID, vaultID uuid.UUID)) *MockSecretService_GetSecretVersionsInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretService_GetSecretVersionsInVault_Call) Return(_a0 []model.SecretVersion, _a1 error) *MockSecretService_GetSecretVersionsInVault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GetSecretVersionsInVault_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]model.SecretVersion, error)) *MockSecretService_GetSecretVersionsInVault_Call {
	_c.Call.Return(run)
	return _c
}

// ImportSecrets provides a mock function with given fields: ctx, req
func (_m *MockSecretService) ImportSecrets(ctx context.Context, req secrets.ImportSecretsRequest) (*secrets.ImportResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ImportSecrets")
	}

	var r0 *secrets.ImportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.ImportSecretsRequest) (*secrets.ImportResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, secrets.ImportSecretsRequest) *secrets.ImportResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secrets.ImportResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, secrets.ImportSecretsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_ImportSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportSecrets'
type MockSecretService_ImportSecrets_Call struct {
	*mock.Call
}

// ImportSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.ImportSecretsRequest
func (_e *MockSecretService_Expecter) ImportSecrets(ctx interface{}, req interface{}) *MockSecretService_ImportSecrets_Call {
	return &MockSecretService_ImportSecrets_Call{Call: _e.mock.On("ImportSecrets", ctx, req)}
}

func (_c *MockSecretService_ImportSecrets_Call) Run(run func(ctx context.Context, req secrets.ImportSecretsRequest)) *MockSecretService_ImportSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.ImportSecretsRequest))
	})
	return _c
}

func (_c *MockSecretService_ImportSecrets_Call) Return(_a0 *secrets.ImportResult, _a1 error) *MockSecretService_ImportSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_ImportSecrets_Call) RunAndReturn(run func(context.Context, secrets.ImportSecretsRequest) (*secrets.ImportResult, error)) *MockSecretService_ImportSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeletedSecretsScoped provides a mock function with given fields: ctx, scope
func (_m *MockSecretService) ListDeletedSecretsScoped(ctx context.Context, scope model.Scope) ([]model.Secret, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for ListDeletedSecretsScoped")
	}

	var r0 []model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) ([]model.Secret, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) []model.Secret); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_ListDeletedSecretsScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeletedSecretsScoped'
type MockSecretService_ListDeletedSecretsScoped_Call struct {
	*mock.Call
}

// ListDeletedSecretsScoped is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
func (_e *MockSecretService_Expecter) ListDeletedSecretsScoped(ctx interface{}, scope interface{}) *MockSecretService_ListDeletedSecretsScoped_Call {
	return &MockSecretService_ListDeletedSecretsScoped_Call{Call: _e.mock.On("ListDeletedSecretsScoped", ctx, scope)}
}

func (_c *MockSecretService_ListDeletedSecretsScoped_Call) Run(run func(ctx context.Context, scope model.Scope)) *MockSecretService_ListDeletedSecretsScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope))
	})
	return _c
}

func (_c *MockSecretService_ListDeletedSecretsScoped_Call) Return(_a0 []model.Secret, _a1 error) *MockSecretService_ListDeletedSecretsScoped_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_ListDeletedSecretsScoped_Call) RunAndReturn(run func(context.Context, model.Scope) ([]model.Secret, error)) *MockSecretService_ListDeletedSecretsScoped_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecrets provides a mock function with given fields: ctx, userID, tags
func (_m *MockSecretService) ListSecrets(ctx context.Context, userID uuid.UUID, tags []string) ([]model.Secret, error) {
	ret := _m.Called(ctx, userID, tags)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 []model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) ([]model.Secret, error)); ok {
		return rf(ctx, userID, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) []model.Secret); ok {
		r0 = rf(ctx, userID, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []string) error); ok {
		r1 = rf(ctx, userID, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_ListSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecrets'
type MockSecretService_ListSecrets_Call struct {
	*mock.Call
}

// ListSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tags []string
func (_e *MockSecretService_Expecter) ListSecrets(ctx interface{}, userID interface{}, tags interface{}) *MockSecretService_ListSecrets_Call {
	return &MockSecretService_ListSecrets_Call{Call: _e.mock.On("ListSecrets", ctx, userID, tags)}
}

func (_c *MockSecretService_ListSecrets_Call) Run(run func(ctx context.Context, userID uuid.UUID, tags []string)) *MockSecretService_ListSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]string))
	})
	return _c
}

func (_c *MockSecretService_ListSecrets_Call) Return(_a0 []model.Secret, _a1 error) *MockSecretService_ListSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_ListSecrets_Call) RunAndReturn(run func(context.Context, uuid.UUID, []string) ([]model.Secret, error)) *MockSecretService_ListSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecretsInVault provides a mock function with given fields: ctx, vaultID, tags
func (_m *MockSecretService) ListSecretsInVault(ctx context.Context, vaultID uuid.UUID, tags []string) ([]model.Secret, error) {
	ret := _m.Called(ctx, vaultID, tags)

	if len(ret) == 0 {
		panic("no return value specified for ListSecretsInVault")
	}

	var r0 []model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) ([]model.Secret, error)); ok {
		return rf(ctx, vaultID, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) []model.Secret); ok {
		r0 = rf(ctx, vaultID, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []string) error); ok {
		r1 = rf(ctx, vaultID, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_ListSecretsInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecretsInVault'
type MockSecretService_ListSecretsInVault_Call struct {
	*mock.Call
}

// ListSecretsInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID uuid.UUID
//   - tags []string
func (_e *MockSecretService_Expecter) ListSecretsInVault(ctx interface{}, vaultID interface{}, tags interface{}) *MockSecretService_ListSecretsInVault_Call {
	return &MockSecretService_ListSecretsInVault_Call{Call: _e.mock.On("ListSecretsInVault", ctx, vaultID, tags)}
}

func (_c *MockSecretService_ListSecretsInVault_Call) Run(run func(ctx context.Context, vaultID uuid.UUID, tags []string)) *MockSecretService_ListSecretsInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]string))
	})
	return _c
}

func (_c *MockSecretService_ListSecretsInVault_Call) Return(_a0 []model.Secret, _a1 error) *MockSecretService_ListSecretsInVault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_ListSecretsInVault_Call) RunAndReturn(run func(context.Context, uuid.UUID, []string) ([]model.Secret, error)) *MockSecretService_ListSecretsInVault_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecretsScoped provides a mock function with given fields: ctx, scope, tags
func (_m *MockSecretService) ListSecretsScoped(ctx context.Context, scope model.Scope, tags []string) ([]model.Secret, error) {
	ret := _m.Called(ctx, scope, tags)

	if len(ret) == 0 {
		panic("no return value specified for ListSecretsScoped")
	}

	var r0 []model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, []string) ([]model.Secret, error)); ok {
		return rf(ctx, scope, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, []string) []model.Secret); ok {
		r0 = rf(ctx, scope, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope, []string) error); ok {
		r1 = rf(ctx, scope, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_ListSecretsScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecretsScoped'
type MockSecretService_ListSecretsScoped_Call struct {
	*mock.Call
}

// ListSecretsScoped is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
//   - tags []string
func (_e *MockSecretService_Expecter) ListSecretsScoped(ctx interface{}, scope interface{}, tags interface{}) *MockSecretService_ListSecretsScoped_Call {
	return &MockSecretService_ListSecretsScoped_Call{Call: _e.mock.On("ListSecretsScoped", ctx, scope, tags)}
}

func (_c *MockSecretService_ListSecretsScoped_Call) Run(run func(ctx context.Context, scope model.Scope, tags []string)) *MockSecretService_ListSecretsScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope), args[2].([]string))
	})
	return _c
}

func (_c *MockSecretService_ListSecretsScoped_Call) Return(_a0 []model.Secret, _a1 error) *MockSecretService_ListSecretsScoped_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_ListSecretsScoped_Call) RunAndReturn(run func(context.Context, model.Scope, []string) ([]model.Secret, error)) *MockSecretService_ListSecretsScoped_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeSecretScoped provides a mock function with given fields: ctx, secretID, scope
func (_m *MockSecretService) PurgeSecretScoped(ctx context.Context, secretID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, secretID, scope)

	if len(ret) == 0 {
		panic("no return value specified for PurgeSecretScoped")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, secretID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretService_PurgeSecretScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeSecretScoped'
type MockSecretService_PurgeSecretScoped_Call struct {
	*mock.Call
}

// PurgeSecretScoped is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - scope model.Scope
func (_e *MockSecretService_Expecter) PurgeSecretScoped(ctx interface{}, secretID interface{}, scope interface{}) *MockSecretService_PurgeSecretScoped_Call {
	return &MockSecretService_PurgeSecretScoped_Call{Call: _e.mock.On("PurgeSecretScoped", ctx, secretID, scope)}
}

func (_c *MockSecretService_PurgeSecretScoped_Call) Run(run func(ctx context.Context, secretID uuid.UUID, scope model.Scope)) *MockSecretService_PurgeSecretScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockSecretService_PurgeSecretScoped_Call) Return(_a0 error) *MockSecretService_PurgeSecretScoped_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretService_PurgeSecretScoped_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockSecretService_PurgeSecretScoped_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverSecretScoped provides a mock function with given fields: ctx, secretID, scope
func (_m *MockSecretService) RecoverSecretScoped(ctx context.Context, secretID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, secretID, scope)

	if len(ret) == 0 {
		panic("no return value specified for RecoverSecretScoped")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, secretID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretService_RecoverSecretScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverSecretScoped'
type MockSecretService_RecoverSecretScoped_Call struct {
	*mock.Call
}

// RecoverSecretScoped is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - scope model.Scope
func (_e *MockSecretService_Expecter) RecoverSecretScoped(ctx interface{}, secretID interface{}, scope interface{}) *MockSecretService_RecoverSecretScoped_Call {
	return &MockSecretService_RecoverSecretScoped_Call{Call: _e.mock.On("RecoverSecretScoped", ctx, secretID, scope)}
}

func (_c *MockSecretService_RecoverSecretScoped_Call) Run(run func(ctx context.Context, secretID uuid.UUID, scope model.Scope)) *MockSecretService_RecoverSecretScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockSecretService_RecoverSecretScoped_Call) Return(_a0 error) *MockSecretService_RecoverSecretScoped_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretService_RecoverSecretScoped_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockSecretService_RecoverSecretScoped_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecret provides a mock function with given fields: ctx, req
func (_m *MockSecretService) UpdateSecret(ctx context.Context, req secrets.UpdateSecretRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.UpdateSecretRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretService_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type MockSecretService_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.UpdateSecretRequest
func (_e *MockSecretService_Expecter) UpdateSecret(ctx interface{}, req interface{}) *MockSecretService_UpdateSecret_Call {
	return &MockSecretService_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret", ctx, req)}
}

func (_c *MockSecretService_UpdateSecret_Call) Run(run func(ctx context.Context, req secrets.UpdateSecretRequest)) *MockSecretService_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.UpdateSecretRequest))
	})
	return _c
}

func (_c *MockSecretService_UpdateSecret_Call) Return(_a0 error) *MockSecretService_UpdateSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretService_UpdateSecret_Call) RunAndReturn(run func(context.Context, secrets.UpdateSecretRequest) error) *MockSecretService_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecretInVault provides a mock function with given fields: ctx, req
func (_m *MockSecretService) UpdateSecretInVault(ctx context.Context, req secrets.UpdateSecretRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecretInVault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.UpdateSecretRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretService_UpdateSecretInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecretInVault'
type MockSecretService_UpdateSecretInVault_Call struct {
	*mock.Call
}

// UpdateSecretInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.UpdateSecretRequest
func (_e *MockSecretService_Expecter) UpdateSecretInVault(ctx interface{}, req interface{}) *MockSecretService_UpdateSecretInVault_Call {
	return &MockSecretService_UpdateSecretInVault_Call{Call: _e.mock.On("UpdateSecretInVault", ctx, req)}
}

func (_c *MockSecretService_UpdateSecretInVault_Call) Run(run func(ctx context.Context, req secrets.UpdateSecretRequest)) *MockSecretService_UpdateSecretInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.UpdateSecretRequest))
	})
	return _c
}

func (_c *MockSecretService_UpdateSecretInVault_Call) Return(_a0 error) *MockSecretService_UpdateSecretInVault_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretService_UpdateSecretInVault_Call) RunAndReturn(run func(context.Context, secrets.UpdateSecretRequest) error) *MockSecretService_UpdateSecretInVault_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecretScoped provides a mock function with given fields: ctx, req
func (_m *MockSecretService) UpdateSecretScoped(ctx context.Context, req secrets.UpdateSecretRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecretScoped")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.UpdateSecretRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretService_UpdateSecretScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecretScoped'
type MockSecretService_UpdateSecretScoped_Call struct {
	*mock.Call
}

// UpdateSecretScoped is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.UpdateSecretRequest
func (_e *MockSecretService_Expecter) UpdateSecretScoped(ctx interface{}, req interface{}) *MockSecretService_UpdateSecretScoped_Call {
	return &MockSecretService_UpdateSecretScoped_Call{Call: _e.mock.On("UpdateSecretScoped", ctx, req)}
}

func (_c *MockSecretService_UpdateSecretScoped_Call) Run(run func(ctx context.Context, req secrets.UpdateSecretRequest)) *MockSecretService_UpdateSecretScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.UpdateSecretRequest))
	})
	return _c
}

func (_c *MockSecretService_UpdateSecretScoped_Call) Return(_a0 error) *MockSecretService_UpdateSecretScoped_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretService_UpdateSecretScoped_Call) RunAndReturn(run func(context.Context, secrets.UpdateSecretRequest) error) *MockSecretService_UpdateSecretScoped_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretService creates a new instance of MockSecretService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretService {
	mock := &MockSecretService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
