// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "rocketvault/model"

	mock "github.com/stretchr/testify/mock"

	secrets "rocketvault/internal/services/secrets"

	uuid "github.com/google/uuid"
)

// MockVersioningServiceInterface is an autogenerated mock type for the VersioningServiceInterface type
type MockVersioningServiceInterface struct {
	mock.Mock
}

type MockVersioningServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersioningServiceInterface) EXPECT() *MockVersioningServiceInterface_Expecter {
	return &MockVersioningServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateVersion provides a mock function with given fields: ctx, req
func (_m *MockVersioningServiceInterface) CreateVersion(ctx context.Context, req secrets.CreateVersionRequest) (*model.SecretVersion, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateVersion")
	}

	var r0 *model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.CreateVersionRequest) (*model.SecretVersion, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, secrets.CreateVersionRequest) *model.SecretVersion); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, secrets.CreateVersionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVersioningServiceInterface_CreateVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVersion'
type MockVersioningServiceInterface_CreateVersion_Call struct {
	*mock.Call
}

// CreateVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.CreateVersionRequest
func (_e *MockVersioningServiceInterface_Expecter) CreateVersion(ctx interface{}, req interface{}) *MockVersioningServiceInterface_CreateVersion_Call {
	return &MockVersioningServiceInterface_CreateVersion_Call{Call: _e.mock.On("CreateVersion", ctx, req)}
}

func (_c *MockVersioningServiceInterface_CreateVersion_Call) Run(run func(ctx context.Context, req secrets.CreateVersionRequest)) *MockVersioningServiceInterface_CreateVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.CreateVersionRequest))
	})
	return _c
}

func (_c *MockVersioningServiceInterface_CreateVersion_Call) Return(_a0 *model.SecretVersion, _a1 error) *MockVersioningServiceInterface_CreateVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVersioningServiceInterface_CreateVersion_Call) RunAndReturn(run func(context.Context, secrets.CreateVersionRequest) (*model.SecretVersion, error)) *MockVersioningServiceInterface_CreateVersion_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSpecificVersion provides a mock function with given fields: ctx, secretID, version, userID
func (_m *MockVersioningServiceInterface) DeleteSpecificVersion(ctx context.Context, secretID uuid.UUID, version int, userID uuid.UUID) error {
	ret := _m.Called(ctx, secretID, version, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSpecificVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, uuid.UUID) error); ok {
		r0 = rf(ctx, secretID, version, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVersioningServiceInterface_DeleteSpecificVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSpecificVersion'
type MockVersioningServiceInterface_DeleteSpecificVersion_Call struct {
	*mock.Call
}

// DeleteSpecificVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - version int
//   - userID uuid.UUID
func (_e *MockVersioningServiceInterface_Expecter) DeleteSpecificVersion(ctx interface{}, secretID interface{}, version interface{}, userID interface{}) *MockVersioningServiceInterface_DeleteSpecificVersion_Call {
	return &MockVersioningServiceInterface_DeleteSpecificVersion_Call{Call: _e.mock.On("DeleteSpecificVersion", ctx, secretID, version, userID)}
}

func (_c *MockVersioningServiceInterface_DeleteSpecificVersion_Call) Run(run func(ctx context.Context, secretID uuid.UUID, version int, userID uuid.UUID)) *MockVersioningServiceInterface_DeleteSpecificVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockVersioningServiceInterface_DeleteSpecificVersion_Call) Return(_a0 error) *MockVersioningServiceInterface_DeleteSpecificVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVersioningServiceInterface_DeleteSpecificVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, uuid.UUID) error) *MockVersioningServiceInterface_DeleteSpecificVersion_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVersions provides a mock function with given fields: ctx, secretID, userID
func (_m *MockVersioningServiceInterface) DeleteVersions(ctx context.Context, secretID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, secretID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVersions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, secretID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVersioningServiceInterface_DeleteVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVersions'
type MockVersioningServiceInterface_DeleteVersions_Call struct {
	*mock.Call
}

// DeleteVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - userID uuid.UUID
func (_e *MockVersioningServiceInterface_Expecter) DeleteVersions(ctx interface{}, secretID interface{}, userID interface{}) *MockVersioningServiceInterface_DeleteVersions_Call {
	return &MockVersioningServiceInterface_DeleteVersions_Call{Call: _e.mock.On("DeleteVersions", ctx, secretID, userID)}
}

func (_c *MockVersioningServiceInterface_DeleteVersions_Call) Run(run func(ctx context.Context, secretID uuid.UUID, userID uuid.UUID)) *MockVersioningServiceInterface_DeleteVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockVersioningServiceInterface_DeleteVersions_Call) Return(_a0 error) *MockVersioningServiceInterface_DeleteVersions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVersioningServiceInterface_DeleteVersions_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockVersioningServiceInterface_DeleteVersions_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestVersion provides a mock function with given fields: ctx, secretID, scope
func (_m *MockVersioningServiceInterface) GetLatestVersion(ctx context.Context, secretID uuid.UUID, scope model.Scope) (*model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersion")
	}

	var r0 *model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) (*model.SecretVersion, error)); ok {
		return rf(ctx, secretID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) *model.SecretVersion); ok {
		r0 = rf(ctx, secretID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, secretID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVersioningServiceInterface_GetLatestVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestVersion'
type MockVersioningServiceInterface_GetLatestVersion_Call struct {
	*mock.Call
}

// GetLatestVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - scope model.Scope
func (_e *MockVersioningServiceInterface_Expecter) GetLatestVersion(ctx interface{}, secretID interface{}, scope interface{}) *MockVersioningServiceInterface_GetLatestVersion_Call {
	return &MockVersioningServiceInterface_GetLatestVersion_Call{Call: _e.mock.On("GetLatestVersion", ctx, secretID, scope)}
}

func (_c *MockVersioningServiceInterface_GetLatestVersion_Call) Run(run func(ctx context.Context, secretID uuid.UUID, scope model.Scope)) *MockVersioningServiceInterface_GetLatestVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockVersioningServiceInterface_GetLatestVersion_Call) Return(_a0 *model.SecretVersion, _a1 error) *MockVersioningServiceInterface_GetLatestVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVersioningServiceInterface_GetLatestVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) (*model.SecretVersion, error)) *MockVersioningServiceInterface_GetLatestVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with given fields: ctx, secretID, version, scope
func (_m *MockVersioningServiceInterface) GetVersion(ctx context.Context, secretID uuid.UUID, version int, scope model.Scope) (*model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID, version, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 *model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.Scope) (*model.SecretVersion, error)); ok {
		return rf(ctx, secretID, version, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.Scope) *model.SecretVersion); ok {
		r0 = rf(ctx, secretID, version, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, model.Scope) error); ok {
		r1 = rf(ctx, secretID, version, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVersioningServiceInterface_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockVersioningServiceInterface_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - version int
//   - scope model.Scope
func (_e *MockVersioningServiceInterface_Expecter) GetVersion(ctx interface{}, secretID interface{}, version interface{}, scope interface{}) *MockVersioningServiceInterface_GetVersion_Call {
	return &MockVersioningServiceInterface_GetVersion_Call{Call: _e.mock.On("GetVersion", ctx, secretID, version, scope)}
}

func (_c *MockVersioningServiceInterface_GetVersion_Call) Run(run func(ctx context.Context, secretID uuid.UUID, version int, scope model.Scope)) *MockVersioningServiceInterface_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(model.Scope))
	})
	return _c
}

func (_c *MockVersioningServiceInterface_GetVersion_Call) Return(_a0 *model.SecretVersion, _a1 error) *MockVersioningServiceInterface_GetVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVersioningServiceInterface_GetVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, model.Scope) (*model.SecretVersion, error)) *MockVersioningServiceInterface_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersions provides a mock function with given fields: ctx, secretID, scope
func (_m *MockVersioningServiceInterface) GetVersions(ctx context.Context, secretID uuid.UUID, scope model.Scope) ([]model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetVersions")
	}

	var r0 []model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) ([]model.SecretVersion, error)); ok {
		return rf(ctx, secretID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) []model.SecretVersion); ok {
		r0 = rf(ctx, secretID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, secretID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVersioningServiceInterface_GetVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersions'
type MockVersioningServiceInterface_GetVersions_Call struct {
	*mock.Call
}

// GetVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - scope model.Scope
func (_e *MockVersioningServiceInterface_Expecter) GetVersions(ctx interface{}, secretID interface{}, scope interface{}) *MockVersioningServiceInterface_GetVersions_Call {
	return &MockVersioningServiceInterface_GetVersions_Call{Call: _e.mock.On("GetVersions", ctx, secretID, scope)}
}

func (_c *MockVersioningServiceInterface_GetVersions_Call) Run(run func(ctx context.Context, secretID uuid.UUID, scope model.Scope)) *MockVersioningServiceInterface_GetVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockVersioningServiceInterface_GetVersions_Call) Return(_a0 []model.SecretVersion, _a1 error) *MockVersioningServiceInterface_GetVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVersioningServiceInterface_GetVersions_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) ([]model.SecretVersion, error)) *MockVersioningServiceInterface_GetVersions_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersionsMetadata provides a mock function with given fields: ctx, secretID, scope
func (_m *MockVersioningServiceInterface) GetVersionsMetadata(ctx context.Context, secretID uuid.UUID, scope model.Scope) ([]model.SecretVersionMetadata, error) {
	ret := _m.Called(ctx, secretID, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetVersionsMetadata")
	}

	var r0 []model.SecretVersionMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) ([]model.SecretVersionMetadata, error)); ok {
		return rf(ctx, secretID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) []model.SecretVersionMetadata); ok {
		r0 = rf(ctx, secretID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SecretVersionMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, secretID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVersioningServiceInterface_GetVersionsMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersionsMetadata'
type MockVersioningServiceInterface_GetVersionsMetadata_Call struct {
	*mock.Call
}

// GetVersionsMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - scope model.Scope
func (_e *MockVersioningServiceInterface_Expecter) GetVersionsMetadata(ctx interface{}, secretID interface{}, scope interface{}) *MockVersioningServiceInterface_GetVersionsMetadata_Call {
	return &MockVersioningServiceInterface_GetVersionsMetadata_Call{Call: _e.mock.On("GetVersionsMetadata", ctx, secretID, scope)}
}

func (_c *MockVersioningServiceInterface_GetVersionsMetadata_Call) Run(run func(ctx context.Context, secretID uuid.UUID, scope model.Scope)) *MockVersioningServiceInterface_GetVersionsMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockVersioningServiceInterface_GetVersionsMetadata_Call) Return(_a0 []model.SecretVersionMetadata, _a1 error) *MockVersioningServiceInterface_GetVersionsMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVersioningServiceInterface_GetVersionsMetadata_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) ([]model.SecretVersionMetadata, error)) *MockVersioningServiceInterface_GetVersionsMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackToVersion provides a mock function with given fields: ctx, req
func (_m *MockVersioningServiceInterface) RollbackToVersion(ctx context.Context, req secrets.RollbackRequest) (*model.Secret, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RollbackToVersion")
	}

	var r0 *model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.RollbackRequest) (*model.Secret, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, secrets.RollbackRequest) *model.Secret); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, secrets.RollbackRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVersioningServiceInterface_RollbackToVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackToVersion'
type MockVersioningServiceInterface_RollbackToVersion_Call struct {
	*mock.Call
}

// RollbackToVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.RollbackRequest
func (_e *MockVersioningServiceInterface_Expecter) RollbackToVersion(ctx interface{}, req interface{}) *MockVersioningServiceInterface_RollbackToVersion_Call {
	return &MockVersioningServiceInterface_RollbackToVersion_Call{Call: _e.mock.On("RollbackToVersion", ctx, req)}
}

func (_c *MockVersioningServiceInterface_RollbackToVersion_Call) Run(run func(ctx context.Context, req secrets.RollbackRequest)) *MockVersioningServiceInterface_RollbackToVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.RollbackRequest))
	})
	return _c
}

func (_c *MockVersioningServiceInterface_RollbackToVersion_Call) Return(_a0 *model.Secret, _a1 error) *MockVersioningServiceInterface_RollbackToVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVersioningServiceInterface_RollbackToVersion_Call) RunAndReturn(run func(context.Context, secrets.RollbackRequest) (*model.Secret, error)) *MockVersioningServiceInterface_RollbackToVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVersioningServiceInterface creates a new instance of MockVersioningServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersioningServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersioningServiceInterface {
	mock := &MockVersioningServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
