// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "rocketvault/model"

	mock "github.com/stretchr/testify/mock"

	secrets "rocketvault/internal/services/secrets"

	uuid "github.com/google/uuid"
)

// MockSecretService is an autogenerated mock type for the SecretService type
type MockSecretService struct {
	mock.Mock
}

type MockSecretService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretService) EXPECT() *MockSecretService_Expecter {
	return &MockSecretService_Expecter{mock: &_m.Mock}
}

// CreateSecret provides a mock function with given fields: ctx, req
func (_m *MockSecretService) CreateSecret(ctx context.Context, req secrets.CreateSecretRequest) (*model.Secret, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 *model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.CreateSecretRequest) (*model.Secret, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, secrets.CreateSecretRequest) *model.Secret); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, secrets.CreateSecretRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockSecretService_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.CreateSecretRequest
func (_e *MockSecretService_Expecter) CreateSecret(ctx interface{}, req interface{}) *MockSecretService_CreateSecret_Call {
	return &MockSecretService_CreateSecret_Call{Call: _e.mock.On("CreateSecret", ctx, req)}
}

func (_c *MockSecretService_CreateSecret_Call) Run(run func(ctx context.Context, req secrets.CreateSecretRequest)) *MockSecretService_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.CreateSecretRequest))
	})
	return _c
}

func (_c *MockSecretService_CreateSecret_Call) Return(_a0 *model.Secret, _a1 error) *MockSecretService_CreateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_CreateSecret_Call) RunAndReturn(run func(context.Context, secrets.CreateSecretRequest) (*model.Secret, error)) *MockSecretService_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function with given fields: ctx, secretID, scope
func (_m *MockSecretService) DeleteSecret(ctx context.Context, secretID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, secretID, scope)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, secretID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretService_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockSecretService_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - scope model.Scope
func (_e *MockSecretService_Expecter) DeleteSecret(ctx interface{}, secretID interface{}, scope interface{}) *MockSecretService_DeleteSecret_Call {
	return &MockSecretService_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, secretID, scope)}
}

func (_c *MockSecretService_DeleteSecret_Call) Run(run func(ctx context.Context, secretID uuid.UUID, scope model.Scope)) *MockSecretService_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockSecretService_DeleteSecret_Call) Return(_a0 error) *MockSecretService_DeleteSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretService_DeleteSecret_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockSecretService_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// ExportSecrets provides a mock function with given fields: ctx, req
func (_m *MockSecretService) ExportSecrets(ctx context.Context, req secrets.ExportSecretsRequest) ([]byte, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ExportSecrets")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.ExportSecretsRequest) ([]byte, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, secrets.ExportSecretsRequest) []byte); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, secrets.ExportSecretsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_ExportSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportSecrets'
type MockSecretService_ExportSecrets_Call struct {
	*mock.Call
}

// ExportSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.ExportSecretsRequest
func (_e *MockSecretService_Expecter) ExportSecrets(ctx interface{}, req interface{}) *MockSecretService_ExportSecrets_Call {
	return &MockSecretService_ExportSecrets_Call{Call: _e.mock.On("ExportSecrets", ctx, req)}
}

func (_c *MockSecretService_ExportSecrets_Call) Run(run func(ctx context.Context, req secrets.ExportSecretsRequest)) *MockSecretService_ExportSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.ExportSecretsRequest))
	})
	return _c
}

func (_c *MockSecretService_ExportSecrets_Call) Return(_a0 []byte, _a1 error) *MockSecretService_ExportSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_ExportSecrets_Call) RunAndReturn(run func(context.Context, secrets.ExportSecretsRequest) ([]byte, error)) *MockSecretService_ExportSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateSecret provides a mock function with given fields: ctx, req
func (_m *MockSecretService) GenerateSecret(ctx context.Context, req secrets.GenerateSecretRequest) (*model.Secret, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSecret")
	}

	var r0 *model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.GenerateSecretRequest) (*model.Secret, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, secrets.GenerateSecretRequest) *model.Secret); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, secrets.GenerateSecretRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GenerateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSecret'
type MockSecretService_GenerateSecret_Call struct {
	*mock.Call
}

// GenerateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.GenerateSecretRequest
func (_e *MockSecretService_Expecter) GenerateSecret(ctx interface{}, req interface{}) *MockSecretService_GenerateSecret_Call {
	return &MockSecretService_GenerateSecret_Call{Call: _e.mock.On("GenerateSecret", ctx, req)}
}

func (_c *MockSecretService_GenerateSecret_Call) Run(run func(ctx context.Context, req secrets.GenerateSecretRequest)) *MockSecretService_GenerateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.GenerateSecretRequest))
	})
	return _c
}

func (_c *MockSecretService_GenerateSecret_Call) Return(_a0 *model.Secret, _a1 error) *MockSecretService_GenerateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GenerateSecret_Call) RunAndReturn(run func(context.Context, secrets.GenerateSecretRequest) (*model.Secret, error)) *MockSecretService_GenerateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestSecretVersion provides a mock function with given fields: ctx, secretID, scope
func (_m *MockSecretService) GetLatestSecretVersion(ctx context.Context, secretID uuid.UUID, scope model.Scope) (*model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSecretVersion")
	}

	var r0 *model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) (*model.SecretVersion, error)); ok {
		return rf(ctx, secretID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) *model.SecretVersion); ok {
		r0 = rf(ctx, secretID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, secretID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GetLatestSecretVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestSecretVersion'
type MockSecretService_GetLatestSecretVersion_Call struct {
	*mock.Call
}

// GetLatestSecretVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - scope model.Scope
func (_e *MockSecretService_Expecter) GetLatestSecretVersion(ctx interface{}, secretID interface{}, scope interface{}) *MockSecretService_GetLatestSecretVersion_Call {
	return &MockSecretService_GetLatestSecretVersion_Call{Call: _e.mock.On("GetLatestSecretVersion", ctx, secretID, scope)}
}

func (_c *MockSecretService_GetLatestSecretVersion_Call) Run(run func(ctx context.Context, secretID uuid.UUID, scope model.Scope)) *MockSecretService_GetLatestSecretVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockSecretService_GetLatestSecretVersion_Call) Return(_a0 *model.SecretVersion, _a1 error) *MockSecretService_GetLatestSecretVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GetLatestSecretVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) (*model.SecretVersion, error)) *MockSecretService_GetLatestSecretVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function with given fields: ctx, secretID, scope
func (_m *MockSecretService) GetSecret(ctx context.Context, secretID uuid.UUID, scope model.Scope) (*model.Secret, error) {
	ret := _m.Called(ctx, secretID, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) (*model.Secret, error)); ok {
		return rf(ctx, secretID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) *model.Secret); ok {
		r0 = rf(ctx, secretID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, secretID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockSecretService_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - scope model.Scope
func (_e *MockSecretService_Expecter) GetSecret(ctx interface{}, secretID interface{}, scope interface{}) *MockSecretService_GetSecret_Call {
	return &MockSecretService_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, secretID, scope)}
}

func (_c *MockSecretService_GetSecret_Call) Run(run func(ctx context.Context, secretID uuid.UUID, scope model.Scope)) *MockSecretService_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockSecretService_GetSecret_Call) Return(_a0 *model.Secret, _a1 error) *MockSecretService_GetSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GetSecret_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) (*model.Secret, error)) *MockSecretService_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretVersion provides a mock function with given fields: ctx, secretID, version, scope
func (_m *MockSecretService) GetSecretVersion(ctx context.Context, secretID uuid.UUID, version int, scope model.Scope) (*model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID, version, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretVersion")
	}

	var r0 *model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.Scope) (*model.SecretVersion, error)); ok {
		return rf(ctx, secretID, version, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.Scope) *model.SecretVersion); ok {
		r0 = rf(ctx, secretID, version, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, model.Scope) error); ok {
		r1 = rf(ctx, secretID, version, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GetSecretVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretVersion'
type MockSecretService_GetSecretVersion_Call struct {
	*mock.Call
}

// GetSecretVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - version int
//   - scope model.Scope
func (_e *MockSecretService_Expecter) GetSecretVersion(ctx interface{}, secretID interface{}, version interface{}, scope interface{}) *MockSecretService_GetSecretVersion_Call {
	return &MockSecretService_GetSecretVersion_Call{Call: _e.mock.On("GetSecretVersion", ctx, secretID, version, scope)}
}

func (_c *MockSecretService_GetSecretVersion_Call) Run(run func(ctx context.Context, secretID uuid.UUID, version int, scope model.Scope)) *MockSecretService_GetSecretVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(model.Scope))
	})
	return _c
}

func (_c *MockSecretService_GetSecretVersion_Call) Return(_a0 *model.SecretVersion, _a1 error) *MockSecretService_GetSecretVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GetSecretVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, model.Scope) (*model.SecretVersion, error)) *MockSecretService_GetSecretVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretVersions provides a mock function with given fields: ctx, secretID, scope
func (_m *MockSecretService) GetSecretVersions(ctx context.Context, secretID uuid.UUID, scope model.Scope) ([]model.SecretVersion, error) {
	ret := _m.Called(ctx, secretID, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretVersions")
	}

	var r0 []model.SecretVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) ([]model.SecretVersion, error)); ok {
		return rf(ctx, secretID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) []model.SecretVersion); ok {
		r0 = rf(ctx, secretID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SecretVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r1 = rf(ctx, secretID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_GetSecretVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretVersions'
type MockSecretService_GetSecretVersions_Call struct {
	*mock.Call
}

// GetSecretVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - scope model.Scope
func (_e *MockSecretService_Expecter) GetSecretVersions(ctx interface{}, secretID interface{}, scope interface{}) *MockSecretService_GetSecretVersions_Call {
	return &MockSecretService_GetSecretVersions_Call{Call: _e.mock.On("GetSecretVersions", ctx, secretID, scope)}
}

func (_c *MockSecretService_GetSecretVersions_Call) Run(run func(ctx context.Context, secretID uuid.UUID, scope model.Scope)) *MockSecretService_GetSecretVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockSecretService_GetSecretVersions_Call) Return(_a0 []model.SecretVersion, _a1 error) *MockSecretService_GetSecretVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_GetSecretVersions_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) ([]model.SecretVersion, error)) *MockSecretService_GetSecretVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ImportSecrets provides a mock function with given fields: ctx, req
func (_m *MockSecretService) ImportSecrets(ctx context.Context, req secrets.ImportSecretsRequest) (*secrets.ImportResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ImportSecrets")
	}

	var r0 *secrets.ImportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.ImportSecretsRequest) (*secrets.ImportResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, secrets.ImportSecretsRequest) *secrets.ImportResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secrets.ImportResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, secrets.ImportSecretsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_ImportSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportSecrets'
type MockSecretService_ImportSecrets_Call struct {
	*mock.Call
}

// ImportSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.ImportSecretsRequest
func (_e *MockSecretService_Expecter) ImportSecrets(ctx interface{}, req interface{}) *MockSecretService_ImportSecrets_Call {
	return &MockSecretService_ImportSecrets_Call{Call: _e.mock.On("ImportSecrets", ctx, req)}
}

func (_c *MockSecretService_ImportSecrets_Call) Run(run func(ctx context.Context, req secrets.ImportSecretsRequest)) *MockSecretService_ImportSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.ImportSecretsRequest))
	})
	return _c
}

func (_c *MockSecretService_ImportSecrets_Call) Return(_a0 *secrets.ImportResult, _a1 error) *MockSecretService_ImportSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_ImportSecrets_Call) RunAndReturn(run func(context.Context, secrets.ImportSecretsRequest) (*secrets.ImportResult, error)) *MockSecretService_ImportSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeletedSecrets provides a mock function with given fields: ctx, scope
func (_m *MockSecretService) ListDeletedSecrets(ctx context.Context, scope model.Scope) ([]model.Secret, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for ListDeletedSecrets")
	}

	var r0 []model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) ([]model.Secret, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope) []model.Secret); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_ListDeletedSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeletedSecrets'
type MockSecretService_ListDeletedSecrets_Call struct {
	*mock.Call
}

// ListDeletedSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
func (_e *MockSecretService_Expecter) ListDeletedSecrets(ctx interface{}, scope interface{}) *MockSecretService_ListDeletedSecrets_Call {
	return &MockSecretService_ListDeletedSecrets_Call{Call: _e.mock.On("ListDeletedSecrets", ctx, scope)}
}

func (_c *MockSecretService_ListDeletedSecrets_Call) Run(run func(ctx context.Context, scope model.Scope)) *MockSecretService_ListDeletedSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope))
	})
	return _c
}

func (_c *MockSecretService_ListDeletedSecrets_Call) Return(_a0 []model.Secret, _a1 error) *MockSecretService_ListDeletedSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_ListDeletedSecrets_Call) RunAndReturn(run func(context.Context, model.Scope) ([]model.Secret, error)) *MockSecretService_ListDeletedSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecrets provides a mock function with given fields: ctx, scope, tags
func (_m *MockSecretService) ListSecrets(ctx context.Context, scope model.Scope, tags []string) ([]model.Secret, error) {
	ret := _m.Called(ctx, scope, tags)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 []model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, []string) ([]model.Secret, error)); ok {
		return rf(ctx, scope, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Scope, []string) []model.Secret); ok {
		r0 = rf(ctx, scope, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Scope, []string) error); ok {
		r1 = rf(ctx, scope, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretService_ListSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecrets'
type MockSecretService_ListSecrets_Call struct {
	*mock.Call
}

// ListSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - scope model.Scope
//   - tags []string
func (_e *MockSecretService_Expecter) ListSecrets(ctx interface{}, scope interface{}, tags interface{}) *MockSecretService_ListSecrets_Call {
	return &MockSecretService_ListSecrets_Call{Call: _e.mock.On("ListSecrets", ctx, scope, tags)}
}

func (_c *MockSecretService_ListSecrets_Call) Run(run func(ctx context.Context, scope model.Scope, tags []string)) *MockSecretService_ListSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Scope), args[2].([]string))
	})
	return _c
}

func (_c *MockSecretService_ListSecrets_Call) Return(_a0 []model.Secret, _a1 error) *MockSecretService_ListSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretService_ListSecrets_Call) RunAndReturn(run func(context.Context, model.Scope, []string) ([]model.Secret, error)) *MockSecretService_ListSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeSecret provides a mock function with given fields: ctx, secretID, scope
func (_m *MockSecretService) PurgeSecret(ctx context.Context, secretID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, secretID, scope)

	if len(ret) == 0 {
		panic("no return value specified for PurgeSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, secretID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretService_PurgeSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeSecret'
type MockSecretService_PurgeSecret_Call struct {
	*mock.Call
}

// PurgeSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - scope model.Scope
func (_e *MockSecretService_Expecter) PurgeSecret(ctx interface{}, secretID interface{}, scope interface{}) *MockSecretService_PurgeSecret_Call {
	return &MockSecretService_PurgeSecret_Call{Call: _e.mock.On("PurgeSecret", ctx, secretID, scope)}
}

func (_c *MockSecretService_PurgeSecret_Call) Run(run func(ctx context.Context, secretID uuid.UUID, scope model.Scope)) *MockSecretService_PurgeSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockSecretService_PurgeSecret_Call) Return(_a0 error) *MockSecretService_PurgeSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretService_PurgeSecret_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockSecretService_PurgeSecret_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverSecret provides a mock function with given fields: ctx, secretID, scope
func (_m *MockSecretService) RecoverSecret(ctx context.Context, secretID uuid.UUID, scope model.Scope) error {
	ret := _m.Called(ctx, secretID, scope)

	if len(ret) == 0 {
		panic("no return value specified for RecoverSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Scope) error); ok {
		r0 = rf(ctx, secretID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretService_RecoverSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverSecret'
type MockSecretService_RecoverSecret_Call struct {
	*mock.Call
}

// RecoverSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
//   - scope model.Scope
func (_e *MockSecretService_Expecter) RecoverSecret(ctx interface{}, secretID interface{}, scope interface{}) *MockSecretService_RecoverSecret_Call {
	return &MockSecretService_RecoverSecret_Call{Call: _e.mock.On("RecoverSecret", ctx, secretID, scope)}
}

func (_c *MockSecretService_RecoverSecret_Call) Run(run func(ctx context.Context, secretID uuid.UUID, scope model.Scope)) *MockSecretService_RecoverSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.Scope))
	})
	return _c
}

func (_c *MockSecretService_RecoverSecret_Call) Return(_a0 error) *MockSecretService_RecoverSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretService_RecoverSecret_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.Scope) error) *MockSecretService_RecoverSecret_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecret provides a mock function with given fields: ctx, req
func (_m *MockSecretService) UpdateSecret(ctx context.Context, req secrets.UpdateSecretRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, secrets.UpdateSecretRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretService_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type MockSecretService_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - req secrets.UpdateSecretRequest
func (_e *MockSecretService_Expecter) UpdateSecret(ctx interface{}, req interface{}) *MockSecretService_UpdateSecret_Call {
	return &MockSecretService_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret", ctx, req)}
}

func (_c *MockSecretService_UpdateSecret_Call) Run(run func(ctx context.Context, req secrets.UpdateSecretRequest)) *MockSecretService_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(secrets.UpdateSecretRequest))
	})
	return _c
}

func (_c *MockSecretService_UpdateSecret_Call) Return(_a0 error) *MockSecretService_UpdateSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretService_UpdateSecret_Call) RunAndReturn(run func(context.Context, secrets.UpdateSecretRequest) error) *MockSecretService_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretService creates a new instance of MockSecretService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretService {
	mock := &MockSecretService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
