# Database configuration for the password manager application.
database:
  # Driver specifies the database type to use.
  # Expected values: "sqlite3" for SQLite or "postgres" for PostgreSQL.
  # Example: sqlite3
  driver: sqlite3
  # DSN (Data Source Name) specifies the database connection string.
  # For SQLite, provide the file path (e.g., "secrets.db").
  # For PostgreSQL, use the format: "host=localhost port=5432 user=user password=pass dbname=secrets sslmode=disable".
  # Example: secrets.db
  dsn: secrets.db

# API server configuration.
api:
  # Port specifies the TCP port for the RESTful API server.
  # Must be a valid port number (1-65535).
  # Example: 8080
  port: 8080

# Logging configuration for github.com/sirupsen/logrus.
log:
  # Path to the log file.
  # Example: password-manager.log
  file: password-manager.log
  
  # Log level (debug, info, warn, error, fatal).
  # Default: debug
  level: debug

# Authentication configuration.
auth:
  # JWT token for CLI commands, obtained via the /login endpoint.
  # Replace with a valid token after logging in.
  # Example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InNkMiIsInJvbGUiOiJTZWNyZXRzTWFuYWdlciIsImV4cCI6MTc0NjE4MDc0NywiaWF0IjoxNzQ2MDk0MzQ3fQ.735MTClpLVhVrbf8NpE3iYKpjGq4BuPg1_iNS-1xnU4"
  # Secret key for signing JWT tokens.
  # Replace with a secure, random string (at least 32 characters).
  # Example: your-jwt-secret
  jwt_secret: "your-jwt-secret"

# Encryption configuration.
# Master key for encrypting secrets (e.g., passwords, API keys).
# Replace with a secure, random 32-byte key for AES-256 encryption.
# Example: your-secure-master-key
master_key: "your-secure-master-key"