// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	certificates "rocketvault/internal/services/certificates"

	mock "github.com/stretchr/testify/mock"

	model "rocketvault/model"

	uuid "github.com/google/uuid"
)

// MockCertificateService is an autogenerated mock type for the CertificateService type
type MockCertificateService struct {
	mock.Mock
}

type MockCertificateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCertificateService) EXPECT() *MockCertificateService_Expecter {
	return &MockCertificateService_Expecter{mock: &_m.Mock}
}

// CreateCASignedCertificate provides a mock function with given fields: ctx, req
func (_m *MockCertificateService) CreateCASignedCertificate(ctx context.Context, req certificates.CreateCertificateRequest) (*certificates.CreateCertificateResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCASignedCertificate")
	}

	var r0 *certificates.CreateCertificateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, certificates.CreateCertificateRequest) (*certificates.CreateCertificateResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, certificates.CreateCertificateRequest) *certificates.CreateCertificateResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificates.CreateCertificateResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, certificates.CreateCertificateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_CreateCASignedCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCASignedCertificate'
type MockCertificateService_CreateCASignedCertificate_Call struct {
	*mock.Call
}

// CreateCASignedCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - req certificates.CreateCertificateRequest
func (_e *MockCertificateService_Expecter) CreateCASignedCertificate(ctx interface{}, req interface{}) *MockCertificateService_CreateCASignedCertificate_Call {
	return &MockCertificateService_CreateCASignedCertificate_Call{Call: _e.mock.On("CreateCASignedCertificate", ctx, req)}
}

func (_c *MockCertificateService_CreateCASignedCertificate_Call) Run(run func(ctx context.Context, req certificates.CreateCertificateRequest)) *MockCertificateService_CreateCASignedCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(certificates.CreateCertificateRequest))
	})
	return _c
}

func (_c *MockCertificateService_CreateCASignedCertificate_Call) Return(_a0 *certificates.CreateCertificateResult, _a1 error) *MockCertificateService_CreateCASignedCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_CreateCASignedCertificate_Call) RunAndReturn(run func(context.Context, certificates.CreateCertificateRequest) (*certificates.CreateCertificateResult, error)) *MockCertificateService_CreateCASignedCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSelfSignedCertificate provides a mock function with given fields: ctx, req
func (_m *MockCertificateService) CreateSelfSignedCertificate(ctx context.Context, req certificates.CreateCertificateRequest) (*certificates.CreateCertificateResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSelfSignedCertificate")
	}

	var r0 *certificates.CreateCertificateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, certificates.CreateCertificateRequest) (*certificates.CreateCertificateResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, certificates.CreateCertificateRequest) *certificates.CreateCertificateResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificates.CreateCertificateResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, certificates.CreateCertificateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_CreateSelfSignedCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSelfSignedCertificate'
type MockCertificateService_CreateSelfSignedCertificate_Call struct {
	*mock.Call
}

// CreateSelfSignedCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - req certificates.CreateCertificateRequest
func (_e *MockCertificateService_Expecter) CreateSelfSignedCertificate(ctx interface{}, req interface{}) *MockCertificateService_CreateSelfSignedCertificate_Call {
	return &MockCertificateService_CreateSelfSignedCertificate_Call{Call: _e.mock.On("CreateSelfSignedCertificate", ctx, req)}
}

func (_c *MockCertificateService_CreateSelfSignedCertificate_Call) Run(run func(ctx context.Context, req certificates.CreateCertificateRequest)) *MockCertificateService_CreateSelfSignedCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(certificates.CreateCertificateRequest))
	})
	return _c
}

func (_c *MockCertificateService_CreateSelfSignedCertificate_Call) Return(_a0 *certificates.CreateCertificateResult, _a1 error) *MockCertificateService_CreateSelfSignedCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_CreateSelfSignedCertificate_Call) RunAndReturn(run func(context.Context, certificates.CreateCertificateRequest) (*certificates.CreateCertificateResult, error)) *MockCertificateService_CreateSelfSignedCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCertificate provides a mock function with given fields: ctx, certID, userID
func (_m *MockCertificateService) DeleteCertificate(ctx context.Context, certID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, certID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, certID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateService_DeleteCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCertificate'
type MockCertificateService_DeleteCertificate_Call struct {
	*mock.Call
}

// DeleteCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - userID uuid.UUID
func (_e *MockCertificateService_Expecter) DeleteCertificate(ctx interface{}, certID interface{}, userID interface{}) *MockCertificateService_DeleteCertificate_Call {
	return &MockCertificateService_DeleteCertificate_Call{Call: _e.mock.On("DeleteCertificate", ctx, certID, userID)}
}

func (_c *MockCertificateService_DeleteCertificate_Call) Run(run func(ctx context.Context, certID uuid.UUID, userID uuid.UUID)) *MockCertificateService_DeleteCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateService_DeleteCertificate_Call) Return(_a0 error) *MockCertificateService_DeleteCertificate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateService_DeleteCertificate_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockCertificateService_DeleteCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCertificateInVault provides a mock function with given fields: ctx, certID, vaultID
func (_m *MockCertificateService) DeleteCertificateInVault(ctx context.Context, certID uuid.UUID, vaultID uuid.UUID) error {
	ret := _m.Called(ctx, certID, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCertificateInVault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, certID, vaultID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateService_DeleteCertificateInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCertificateInVault'
type MockCertificateService_DeleteCertificateInVault_Call struct {
	*mock.Call
}

// DeleteCertificateInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - vaultID uuid.UUID
func (_e *MockCertificateService_Expecter) DeleteCertificateInVault(ctx interface{}, certID interface{}, vaultID interface{}) *MockCertificateService_DeleteCertificateInVault_Call {
	return &MockCertificateService_DeleteCertificateInVault_Call{Call: _e.mock.On("DeleteCertificateInVault", ctx, certID, vaultID)}
}

func (_c *MockCertificateService_DeleteCertificateInVault_Call) Run(run func(ctx context.Context, certID uuid.UUID, vaultID uuid.UUID)) *MockCertificateService_DeleteCertificateInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateService_DeleteCertificateInVault_Call) Return(_a0 error) *MockCertificateService_DeleteCertificateInVault_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateService_DeleteCertificateInVault_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockCertificateService_DeleteCertificateInVault_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificate provides a mock function with given fields: ctx, certID, userID
func (_m *MockCertificateService) GetCertificate(ctx context.Context, certID uuid.UUID, userID uuid.UUID) (*model.Certificate, error) {
	ret := _m.Called(ctx, certID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificate")
	}

	var r0 *model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Certificate, error)); ok {
		return rf(ctx, certID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Certificate); ok {
		r0 = rf(ctx, certID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, certID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_GetCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificate'
type MockCertificateService_GetCertificate_Call struct {
	*mock.Call
}

// GetCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - userID uuid.UUID
func (_e *MockCertificateService_Expecter) GetCertificate(ctx interface{}, certID interface{}, userID interface{}) *MockCertificateService_GetCertificate_Call {
	return &MockCertificateService_GetCertificate_Call{Call: _e.mock.On("GetCertificate", ctx, certID, userID)}
}

func (_c *MockCertificateService_GetCertificate_Call) Run(run func(ctx context.Context, certID uuid.UUID, userID uuid.UUID)) *MockCertificateService_GetCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateService_GetCertificate_Call) Return(_a0 *model.Certificate, _a1 error) *MockCertificateService_GetCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_GetCertificate_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.Certificate, error)) *MockCertificateService_GetCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificateInVault provides a mock function with given fields: ctx, certID, vaultID
func (_m *MockCertificateService) GetCertificateInVault(ctx context.Context, certID uuid.UUID, vaultID uuid.UUID) (*model.Certificate, error) {
	ret := _m.Called(ctx, certID, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificateInVault")
	}

	var r0 *model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Certificate, error)); ok {
		return rf(ctx, certID, vaultID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Certificate); ok {
		r0 = rf(ctx, certID, vaultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, certID, vaultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_GetCertificateInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificateInVault'
type MockCertificateService_GetCertificateInVault_Call struct {
	*mock.Call
}

// GetCertificateInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - vaultID uuid.UUID
func (_e *MockCertificateService_Expecter) GetCertificateInVault(ctx interface{}, certID interface{}, vaultID interface{}) *MockCertificateService_GetCertificateInVault_Call {
	return &MockCertificateService_GetCertificateInVault_Call{Call: _e.mock.On("GetCertificateInVault", ctx, certID, vaultID)}
}

func (_c *MockCertificateService_GetCertificateInVault_Call) Run(run func(ctx context.Context, certID uuid.UUID, vaultID uuid.UUID)) *MockCertificateService_GetCertificateInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateService_GetCertificateInVault_Call) Return(_a0 *model.Certificate, _a1 error) *MockCertificateService_GetCertificateInVault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_GetCertificateInVault_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.Certificate, error)) *MockCertificateService_GetCertificateInVault_Call {
	_c.Call.Return(run)
	return _c
}

// ListCertificates provides a mock function with given fields: ctx, userID
func (_m *MockCertificateService) ListCertificates(ctx context.Context, userID uuid.UUID) ([]model.Certificate, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListCertificates")
	}

	var r0 []model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Certificate, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Certificate); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_ListCertificates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCertificates'
type MockCertificateService_ListCertificates_Call struct {
	*mock.Call
}

// ListCertificates is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCertificateService_Expecter) ListCertificates(ctx interface{}, userID interface{}) *MockCertificateService_ListCertificates_Call {
	return &MockCertificateService_ListCertificates_Call{Call: _e.mock.On("ListCertificates", ctx, userID)}
}

func (_c *MockCertificateService_ListCertificates_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCertificateService_ListCertificates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateService_ListCertificates_Call) Return(_a0 []model.Certificate, _a1 error) *MockCertificateService_ListCertificates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_ListCertificates_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Certificate, error)) *MockCertificateService_ListCertificates_Call {
	_c.Call.Return(run)
	return _c
}

// ListCertificatesInVault provides a mock function with given fields: ctx, vaultID
func (_m *MockCertificateService) ListCertificatesInVault(ctx context.Context, vaultID uuid.UUID) ([]model.Certificate, error) {
	ret := _m.Called(ctx, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for ListCertificatesInVault")
	}

	var r0 []model.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Certificate, error)); ok {
		return rf(ctx, vaultID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Certificate); ok {
		r0 = rf(ctx, vaultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, vaultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_ListCertificatesInVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCertificatesInVault'
type MockCertificateService_ListCertificatesInVault_Call struct {
	*mock.Call
}

// ListCertificatesInVault is a helper method to define mock.On call
//   - ctx context.Context
//   - vaultID uuid.UUID
func (_e *MockCertificateService_Expecter) ListCertificatesInVault(ctx interface{}, vaultID interface{}) *MockCertificateService_ListCertificatesInVault_Call {
	return &MockCertificateService_ListCertificatesInVault_Call{Call: _e.mock.On("ListCertificatesInVault", ctx, vaultID)}
}

func (_c *MockCertificateService_ListCertificatesInVault_Call) Run(run func(ctx context.Context, vaultID uuid.UUID)) *MockCertificateService_ListCertificatesInVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCertificateService_ListCertificatesInVault_Call) Return(_a0 []model.Certificate, _a1 error) *MockCertificateService_ListCertificatesInVault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_ListCertificatesInVault_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Certificate, error)) *MockCertificateService_ListCertificatesInVault_Call {
	_c.Call.Return(run)
	return _c
}

// RenewCertificate provides a mock function with given fields: ctx, certID, userID, validityDays
func (_m *MockCertificateService) RenewCertificate(ctx context.Context, certID uuid.UUID, userID uuid.UUID, validityDays int) (*certificates.CreateCertificateResult, error) {
	ret := _m.Called(ctx, certID, userID, validityDays)

	if len(ret) == 0 {
		panic("no return value specified for RenewCertificate")
	}

	var r0 *certificates.CreateCertificateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) (*certificates.CreateCertificateResult, error)); ok {
		return rf(ctx, certID, userID, validityDays)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) *certificates.CreateCertificateResult); ok {
		r0 = rf(ctx, certID, userID, validityDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificates.CreateCertificateResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r1 = rf(ctx, certID, userID, validityDays)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCertificateService_RenewCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewCertificate'
type MockCertificateService_RenewCertificate_Call struct {
	*mock.Call
}

// RenewCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - userID uuid.UUID
//   - validityDays int
func (_e *MockCertificateService_Expecter) RenewCertificate(ctx interface{}, certID interface{}, userID interface{}, validityDays interface{}) *MockCertificateService_RenewCertificate_Call {
	return &MockCertificateService_RenewCertificate_Call{Call: _e.mock.On("RenewCertificate", ctx, certID, userID, validityDays)}
}

func (_c *MockCertificateService_RenewCertificate_Call) Run(run func(ctx context.Context, certID uuid.UUID, userID uuid.UUID, validityDays int)) *MockCertificateService_RenewCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int))
	})
	return _c
}

func (_c *MockCertificateService_RenewCertificate_Call) Return(_a0 *certificates.CreateCertificateResult, _a1 error) *MockCertificateService_RenewCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCertificateService_RenewCertificate_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int) (*certificates.CreateCertificateResult, error)) *MockCertificateService_RenewCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCertificate provides a mock function with given fields: ctx, req
func (_m *MockCertificateService) UpdateCertificate(ctx context.Context, req certificates.UpdateCertificateRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, certificates.UpdateCertificateRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateService_UpdateCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCertificate'
type MockCertificateService_UpdateCertificate_Call struct {
	*mock.Call
}

// UpdateCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - req certificates.UpdateCertificateRequest
func (_e *MockCertificateService_Expecter) UpdateCertificate(ctx interface{}, req interface{}) *MockCertificateService_UpdateCertificate_Call {
	return &MockCertificateService_UpdateCertificate_Call{Call: _e.mock.On("UpdateCertificate", ctx, req)}
}

func (_c *MockCertificateService_UpdateCertificate_Call) Run(run func(ctx context.Context, req certificates.UpdateCertificateRequest)) *MockCertificateService_UpdateCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(certificates.UpdateCertificateRequest))
	})
	return _c
}

func (_c *MockCertificateService_UpdateCertificate_Call) Return(_a0 error) *MockCertificateService_UpdateCertificate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateService_UpdateCertificate_Call) RunAndReturn(run func(context.Context, certificates.UpdateCertificateRequest) error) *MockCertificateService_UpdateCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCertificateAccess provides a mock function with given fields: ctx, certID, userID, role
func (_m *MockCertificateService) ValidateCertificateAccess(ctx context.Context, certID uuid.UUID, userID uuid.UUID, role string) error {
	ret := _m.Called(ctx, certID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCertificateAccess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, certID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateService_ValidateCertificateAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCertificateAccess'
type MockCertificateService_ValidateCertificateAccess_Call struct {
	*mock.Call
}

// ValidateCertificateAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - certID uuid.UUID
//   - userID uuid.UUID
//   - role string
func (_e *MockCertificateService_Expecter) ValidateCertificateAccess(ctx interface{}, certID interface{}, userID interface{}, role interface{}) *MockCertificateService_ValidateCertificateAccess_Call {
	return &MockCertificateService_ValidateCertificateAccess_Call{Call: _e.mock.On("ValidateCertificateAccess", ctx, certID, userID, role)}
}

func (_c *MockCertificateService_ValidateCertificateAccess_Call) Run(run func(ctx context.Context, certID uuid.UUID, userID uuid.UUID, role string)) *MockCertificateService_ValidateCertificateAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockCertificateService_ValidateCertificateAccess_Call) Return(_a0 error) *MockCertificateService_ValidateCertificateAccess_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateService_ValidateCertificateAccess_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *MockCertificateService_ValidateCertificateAccess_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateKeyOwnership provides a mock function with given fields: ctx, keyID, userID, role
func (_m *MockCertificateService) ValidateKeyOwnership(ctx context.Context, keyID uuid.UUID, userID uuid.UUID, role string) error {
	ret := _m.Called(ctx, keyID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for ValidateKeyOwnership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, keyID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCertificateService_ValidateKeyOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateKeyOwnership'
type MockCertificateService_ValidateKeyOwnership_Call struct {
	*mock.Call
}

// ValidateKeyOwnership is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID uuid.UUID
//   - userID uuid.UUID
//   - role string
func (_e *MockCertificateService_Expecter) ValidateKeyOwnership(ctx interface{}, keyID interface{}, userID interface{}, role interface{}) *MockCertificateService_ValidateKeyOwnership_Call {
	return &MockCertificateService_ValidateKeyOwnership_Call{Call: _e.mock.On("ValidateKeyOwnership", ctx, keyID, userID, role)}
}

func (_c *MockCertificateService_ValidateKeyOwnership_Call) Run(run func(ctx context.Context, keyID uuid.UUID, userID uuid.UUID, role string)) *MockCertificateService_ValidateKeyOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockCertificateService_ValidateKeyOwnership_Call) Return(_a0 error) *MockCertificateService_ValidateKeyOwnership_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCertificateService_ValidateKeyOwnership_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *MockCertificateService_ValidateKeyOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCertificateService creates a new instance of MockCertificateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCertificateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCertificateService {
	mock := &MockCertificateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
